apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-arbeidssokerregisteret-event-prosessor
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 10
  readiness:
    path: /isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  kafka:
    pool: {{ kafka }}
    streams: true
  resources:
    limits:
      memory: 3048Mi
    requests:
      memory: 2048Mi
