varselProducerId = "paw-arbeidssoekerregisteret-min-side-varsler-varsel-producer-v1"
periodeStreamSuffix = "periode-v1"
bekreftelseStreamSuffix = "bekreftelse-v2"
varselHendelseStreamSuffix = "varsel-hendelser-v1"
periodeTopic = "paw.arbeidssokerperioder-v1"
bekreftelseHendelseTopic = "paw.arbeidssoker-bekreftelse-hendelseslogg-v1"
tmsVarselTopic = "min-side.aapen-brukervarsel-v1"
tmsVarselHendelseTopic = "min-side.aapen-varsel-hendelse-v1"
manueltVarselEnabled = true
manueltVarselSchedulingDelay = "PT1M"
manueltVarselSchedulingInterval = "PT5M"
oppryddingEnabled = true
oppryddingSchedulingDelay = "PT1M"
oppryddingSchedulingInterval = "PT5M"
oppryddingEldreEnn = "PT10M"