periodeStreamSuffix = "periode-v1"
bekreftelseStreamSuffix = "bekreftelse-v1"
varselHendelseStreamSuffix = "varsel-hendelser-v1"
periodeTopic = "paw.arbeidssokerperioder-v1"
bekreftelseHendelseTopic = "paw.arbeidssoker-bekreftelse-hendelseslogg-v1"
tmsVarselTopic = "min-side.aapen-brukervarsel-v1"
tmsVarselHendelseTopic = "min-side.aapen-varsel-hendelse-v1"
