periodeAvsluttet:
  link: http://localhost:8080/minside
  sensitivitet: SUBSTANTIAL
  standardSpraak:
    kode: nb
  tekster:
    - spraak:
        kode: nb
      tekst: Du er ikke lengre registrert som arbeidssøker.
    - spraak:
        kode: en
      tekst: You are no longer registered as a jobseeker.
  eksterntVarsel:
    prefererteKanaler:
      - SMS
      - EPOST
    smsTekst: Du er ikke lengre registrert som arbeidssøker. Hilsen Nav
    epostTittel: Du har fått en melding fra Nav
    epostTekst: Hei!\nDu er ikke lengre registrert som arbeidssøker.\nHilsen Nav

bekreftelseTilgjengelig:
  link: http://localhost:8080/minside/bekreftelse
  sensitivitet: SUBSTANTIAL
  standardSpraak:
    kode: nb
  tekster:
    - spraak:
        kode: nb
      tekst: Bekreft at du vil være registrert som arbeidssøker.
    - spraak:
        kode: en
      tekst: Confirm that you want to remain registered as a jobseeker.
  eksterntVarsel:
    prefererteKanaler:
      - SMS
      - EPOST
    smsTekst: Hei! Ønsker du fortsatt å være registrert som arbeidssøker? Logg inn på Nav så snart som mulig for å bekrefte at du vil være registrert. Hilsen Nav
    epostTittel: Du har fått en melding fra Nav
    epostTekst: Hei!\nØnsker du fortsatt å være registrert som arbeidssøker hos Nav? Logg inn på Nav så snart som mulig for å bekrefte at du vil være registrert som arbeidssøker.\nHilsen Nav

manueltVarsel:
  link: http://localhost:8080/minside
  sensitivitet: SUBSTANTIAL
  standardSpraak:
    kode: nb
  tekster:
    - spraak:
        kode: nb
      tekst: Dette er en test av manuelt varsel fra NAV.
    - spraak:
        kode: en
      tekst: This is a test of a manual notification from NAV.
