periodeAvsluttet:
  link: http://localhost:8080/minside
  sensitivitet: SUBSTANTIAL
  standardSpraak:
    kode: nb
  tekster:
    - spraak:
        kode: nb
      tekst: Arbeidssøkerperioden ble avsluttet hos NAV.
    - spraak:
        kode: en
      tekst: Your jobseeker period was ended at NAV.
  eksterntVarsel:
    prefererteKanaler:
      - SMS

bekreftelseTilgjengelig:
  link: http://localhost:8080/minside/bekreftelse
  sensitivitet: SUBSTANTIAL
  standardSpraak:
    kode: nb
  tekster:
    - spraak:
        kode: nb
      tekst: Det er på tide å bekrefte arbeidssøkerperioden din i NAV.
    - spraak:
        kode: en
      tekst: It is time to confirm your jobseeker period in NAV.
  eksterntVarsel:
    prefererteKanaler:
      - SMS
