openapi: "3.0.3"
info:
  title: "paw_arbeidssokerregisteret_api_inngang API"
  description: "paw_arbeidssokerregisteret_api_inngang API"
  version: "1.0.0"
servers:
- url: "https://paw_arbeidssokerregisteret_api_inngang"
paths:
  /api/v1/arbeidssoker/kanStartePeriode:
    put:
      description: "Sjekker om bruker kan registreres som arbeidssøker"
      parameters:
      - name: "Nav-Call-Id"
        in: "header"
        required: false
        schema:
          type: "string"
      - name: "traceparent"
        in: "header"
        required: false
        schema:
          type: "string"
      - name: "Nav-Consumer-Id"
        in: "header"
        required: false
        schema:
          type: "string"
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/KanStarteRequest"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Feil"
        "424":
          description: "Failed Dependency"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Feil"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Feil"
        "403":
          description: "Forbidden"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Feil"
        "204":
          description: "No Content"
          content:
            '*/*':
              schema:
                type: "object"
  /api/v1/arbeidssoker/opplysninger:
    post:
      description: "Registrerer eller oppdaterer brukers opplysninger"
      parameters:
      - name: "Nav-Call-Id"
        in: "header"
        required: false
        schema:
          type: "string"
      - name: "traceparent"
        in: "header"
        required: false
        schema:
          type: "string"
      - name: "Nav-Consumer-Id"
        in: "header"
        required: false
        schema:
          type: "string"
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/OpplysningerRequest"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Feil"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Feil"
        "403":
          description: "Forbidden"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Feil"
        "202":
          description: "Accepted"
          content:
            '*/*':
              schema:
                type: "object"
  /api/v1/arbeidssoker/periode:
    put:
      description: "Registrerer bruker som arbeidssøker"
      parameters:
      - name: "Nav-Call-Id"
        in: "header"
        required: false
        schema:
          type: "string"
      - name: "traceparent"
        in: "header"
        required: false
        schema:
          type: "string"
      - name: "Nav-Consumer-Id"
        in: "header"
        required: false
        schema:
          type: "string"
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/StartStoppRequest"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Feil"
        "424":
          description: "Failed Dependency"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Feil"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Feil"
        "403":
          description: "Forbidden"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Feil"
        "204":
          description: "No Content"
          content:
            '*/*':
              schema:
                type: "object"
  /internal/isAlive:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "ALIVE"
  /internal/isReady:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "READY"
  /internal/metrics:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
components:
  schemas:
    KanStarteRequest:
      type: "object"
      properties:
        identitetsnummer:
          type: "string"
      required:
      - "identitetsnummer"
    AarsakTilAvvisning:
      type: "object"
      properties:
        beskrivelse:
          type: "string"
        regel:
          type: "string"
          enum:
          - "UKJENT_REGEL"
          - "IKKE_FUNNET"
          - "SAVNET"
          - "DOED"
          - "ENDRE_FOR_ANNEN_BRUKER"
          - "ANSATT_IKKE_TILGANG_TIL_BRUKER"
          - "IKKE_TILGANG"
          - "UNDER_18_AAR"
          - "IKKE_BOSATT_I_NORGE_I_HENHOLD_TIL_FOLKEREGISTERLOVEN"
          - "UKJENT_ALDER"
        detaljer:
          type: "array"
          items:
            type: "string"
            enum:
            - "FORHAANDSGODKJENT_AV_ANSATT"
            - "SAMME_SOM_INNLOGGET_BRUKER"
            - "IKKE_SAMME_SOM_INNLOGGER_BRUKER"
            - "ANSATT_IKKE_TILGANG"
            - "ANSATT_TILGANG"
            - "IKKE_ANSATT"
            - "ER_OVER_18_AAR"
            - "ER_UNDER_18_AAR"
            - "UKJENT_FOEDSELSDATO"
            - "UKJENT_FOEDSELSAAR"
            - "TOKENX_PID_IKKE_FUNNET"
            - "OPPHOERT_IDENTITET"
            - "IKKE_BOSATT"
            - "DOED"
            - "SAVNET"
            - "HAR_NORSK_ADRESSE"
            - "HAR_UTENLANDSK_ADRESSE"
            - "INGEN_ADRESSE_FUNNET"
            - "BOSATT_ETTER_FREG_LOVEN"
            - "DNUMMER"
            - "UKJENT_FORENKLET_FREG_STATUS"
            - "HAR_GYLDIG_OPPHOLDSTILLATELSE"
            - "OPPHOLDSTILATELSE_UTGAATT"
            - "BARN_FOEDT_I_NORGE_UTEN_OPPHOLDSTILLATELSE"
            - "INGEN_INFORMASJON_OM_OPPHOLDSTILLATELSE"
            - "UKJENT_STATUS_FOR_OPPHOLDSTILLATELSE"
            - "PERSON_IKKE_FUNNET"
            - "SISTE_FLYTTING_VAR_UT_AV_NORGE"
            - "SISTE_FLYTTING_VAR_INN_TIL_NORGE"
            - "IKKE_MULIG_AA_IDENTIFISERE_SISTE_FLYTTING"
            - "INGEN_FLYTTE_INFORMASJON"
      required:
      - "beskrivelse"
      - "regel"
      - "detaljer"
    Feil:
      type: "object"
      properties:
        melding:
          type: "string"
        feilKode:
          type: "string"
          enum:
          - "UKJENT_FEIL"
          - "UVENTET_FEIL_MOT_EKSTERN_TJENESTE"
          - "FEIL_VED_LESING_AV_FORESPORSEL"
          - "AVVIST"
          - "IKKE_TILGANG"
        aarsakTilAvvisning:
          $ref: "#/components/schemas/AarsakTilAvvisning"
      required:
      - "melding"
      - "feilKode"
    Utdanning:
      type: "object"
      properties:
        nus:
          type: "string"
        bestaatt:
          type: "string"
          enum:
          - "JA"
          - "NEI"
          - "VET_IKKE"
        godkjent:
          type: "string"
          enum:
          - "JA"
          - "NEI"
          - "VET_IKKE"
      required:
      - "nus"
    Helse:
      type: "object"
      properties:
        helsetilstandHindrerArbeid:
          type: "string"
          enum:
          - "JA"
          - "NEI"
          - "VET_IKKE"
      required:
      - "helsetilstandHindrerArbeid"
    JobbsituasjonMedDetaljer:
      type: "object"
      properties:
        beskrivelse:
          type: "string"
          enum:
          - "UKJENT_VERDI"
          - "UDEFINERT"
          - "HAR_SAGT_OPP"
          - "HAR_BLITT_SAGT_OPP"
          - "ER_PERMITTERT"
          - "ALDRI_HATT_JOBB"
          - "IKKE_VAERT_I_JOBB_SISTE_2_AAR"
          - "AKKURAT_FULLFORT_UTDANNING"
          - "VIL_BYTTE_JOBB"
          - "USIKKER_JOBBSITUASJON"
          - "MIDLERTIDIG_JOBB"
          - "DELTIDSJOBB_VIL_MER"
          - "NY_JOBB"
          - "KONKURS"
          - "ANNET"
        detaljer:
          type: "string"
      required:
      - "beskrivelse"
      - "detaljer"
    Jobbsituasjon:
      type: "object"
      properties:
        beskrivelser:
          type: "array"
          items:
            $ref: "#/components/schemas/JobbsituasjonMedDetaljer"
      required:
      - "beskrivelser"
    Annet:
      type: "object"
      properties:
        andreForholdHindrerArbeid:
          type: "string"
          enum:
          - "JA"
          - "NEI"
          - "VET_IKKE"
    OpplysningerOmArbeidssoeker:
      type: "object"
      properties:
        utdanning:
          $ref: "#/components/schemas/Utdanning"
        helse:
          $ref: "#/components/schemas/Helse"
        jobbsituasjon:
          $ref: "#/components/schemas/Jobbsituasjon"
        annet:
          $ref: "#/components/schemas/Annet"
      required:
      - "jobbsituasjon"
    OpplysningerRequest:
      type: "object"
      properties:
        identitetsnummer:
          type: "string"
        opplysningerOmArbeidssoeker:
          $ref: "#/components/schemas/OpplysningerOmArbeidssoeker"
      required:
      - "identitetsnummer"
      - "opplysningerOmArbeidssoeker"
    StartStoppRequest:
      type: "object"
      properties:
        identitetsnummer:
          type: "string"
        registreringForhaandsGodkjentAvAnsatt:
          type: "boolean"
        periodeTilstand:
          type: "string"
          enum:
          - "STARTET"
          - "STOPPET"
      required:
      - "identitetsnummer"
      - "periodeTilstand"