openapi: "3.0.3"
info:
  title: "paw_arbeidssokerregisteret API"
  description: "paw_arbeidssokerregisteret API"
  version: "1.0.0"
servers:
- url: "https://paw_arbeidssokerregisteret"
paths:
  /api/v1/arbeidssoker/periode/start:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/Request"
        required: true
      responses:
        "403":
          description: "Forbidden"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                Example#1:
                  value: "NAV-ansatt har ikke tilgang"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                Example#1:
                  value: "Some json parsing error"
        "424":
          description: "Failed to call downstream service"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                Example#1:
                  value: "Some IO error"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                Example#1:
                  value: "Some weird error"
        "202":
          description: "Accepted"
          content:
            '*/*':
              schema:
                type: "object"
  /api/v1/arbeidssoker/periode/kan-starte:
    put:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/Request"
        required: true
      responses:
        "403":
          description: "Forbidden"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                Example#1:
                  value: "NAV-ansatt har ikke tilgang"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                Example#1:
                  value: "Some json parsing error"
        "424":
          description: "Failed to call downstream service"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                Example#1:
                  value: "Some IO error"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Error"
              examples:
                Example#1:
                  value: "Some weird error"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
  /internal/isAlive:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "ALIVE"
  /internal/isReady:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "READY"
  /internal/metrics:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
components:
  schemas:
    Request:
      type: "object"
      properties:
        identitetsnummer:
          type: "string"
    Error:
      type: "object"
      properties:
        message:
          type: "string"
        errorCode:
          type: "string"
          enum:
            - "UVENTET_FEIL_MOT_EKSTERNE_TJENESTER"
            - "UGYLDIG_JSON"