[pawPeriodeConsumer]
version = 1
topic = "paw.arbeidssokerperioder-v1"
groupIdPrefix = "paw-kafka-key-generator-paw-perioder"

[pdlAktorConsumer]
version = 1
topic = "pdl.aktor-v2"
groupIdPrefix = "paw-kafka-key-generator-pdl-aktor"

[pawIdentitetProducer]
version = 1
topic = "paw.arbeidssoker-identiteter-v1"
clientIdPrefix = "paw-kafka-key-generator-paw-identiteter"

[pawHendelseloggProducer]
version = 1
topic = "paw.arbeidssoker-hendelseslogg-v1"
clientIdPrefix = "paw-kafka-key-generator-paw-hendelseslogg"

[identitetMergeKonfliktJob]
enabled = true
delay = "PT5M"
interval = "PT13M"
batchSize = 10

[identitetSplittKonfliktJob]
enabled = false
delay = "PT4M"
interval = "PT16M"
batchSize = 10