[pawHendelseConsumer]
version = 1
topic = "paw.arbeidssoker-hendelseslogg-v1"
defaultPartitionCount = 6
groupIdPrefix = "paw-kafka-key-generator"

[pawPeriodeConsumer]
version = 1
topic = "paw.arbeidssokerperioder-v1"
defaultPartitionCount = 6
groupIdPrefix = "paw-kafka-key-generator-paw-perioder"

[pdlAktorConsumer]
version = 1
topic = "pdl.aktor-v2"
defaultPartitionCount = 6
groupIdPrefix = "paw-kafka-key-generator-pdl-aktor"