kafkaKeyApiAuthProvider = "azure"

[[providers]]
name = "azure"
discoveryUrl = "http://localhost:8081/default/.well-known/openid-configuration"
acceptedAudience = ["paw-kafka-key-generator"]
requiredClaims = ["NAVident"]
