hendelseTopic = "${KAFKA_PAW_ARBEIDSSOKER_BEKREFTELSE_HENDELSESLOGG_TOPIC}"
bekreftelseTopic = "${KAFKA_PAW_ARBEIDSSOKER_BEKREFTELSE_TOPIC}"
paaVegneAvTopic = "${KAFKA_PAW_ARBEIDSSOKER_BEKREFTELSE_PAAVEGNEAV_TOPIC}"