host = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_BEKREFTELSE_BACKUP_HOST}"
port = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_BEKREFTELSE_BACKUP_PORT}"
username = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_BEKREFTELSE_BACKUP_USERNAME}"
password = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_BEKREFTELSE_BACKUP_PASSWORD}"
name = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_BEKREFTELSE_BACKUP_DATABASE}"
jdbc = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_BEKREFTELSE_BACKUP_JDBC_URL}"
