host = "${NAIS_DATABASE_PAW_KAFKA_KEY_MAINTENANCE_PAWKAFKAKEYSMAINTENANCE_HOST}"
port = "${NAIS_DATABASE_PAW_KAFKA_KEY_MAINTENANCE_PAWKAFKAKEYSMAINTENANCE_PORT}"
username = "${NAIS_DATABASE_PAW_KAFKA_KEY_MAINTENANCE_PAWKAFKAKEYSMAINTENANCE_USERNAME}"
password = "${NAIS_DATABASE_PAW_KAFKA_KEY_MAINTENANCE_PAWKAFKAKEYSMAINTENANCE_PASSWORD}"
name = "${NAIS_DATABASE_PAW_KAFKA_KEY_MAINTENANCE_PAWKAFKAKEYSMAINTENANCE_DATABASE}"
jdbc = "${NAIS_DATABASE_PAW_KAFKA_KEY_MAINTENANCE_PAWKAFKAKEYSMAINTENANCE_URL}"
