version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.apache.kafka.*"
        versions: '>= 4'
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin"
      kafka:
        patterns:
          - "org.apache.kafka"
          - "io.confluent"
          - "org.apache.avro"
      nav:
        patterns:
          - "no.nav"
      logging:
        patterns:
          - "org.slf4j"
          - "ch.qos.logback"
      ktor:
        patterns:
          - "io.ktor"
      jackson:
        patterns:
          - "com.fasterxml.jackson"
