version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      opentelemetry:
        patterns:
          - "io.opentelemetry"
      kotlin:
        patterns:
          - "org.jetbrains.kotlin"
      kafka:
        patterns:
          - "org.apache.kafka"
          - "io.confluent"
          - "org.apache.avro"
        ignore:
          - dependency-name: "org.apache.kafka:kafka-clients"
            versions: '>= 4'
          - dependency-name: "org.apache.kafka:kafka-streams"
            versions: '>= 4'
          - dependency-name: "org.apache.kafka:kafka-streams-test-utils"
            versions: '>= 4'
      nav:
        patterns:
          - "no.nav"
      logging:
        patterns:
          - "org.slf4j"
          - "ch.qos.logback"
      ktor:
        patterns:
          - "io.ktor"
      jackson:
        patterns:
          - "com.fasterxml.jackson"
