applicationIdSuffix = "v2" #TODO: øk til v3 ved fjerning av -test fra hendelselogg-topic i prod
periodeTopic = "paw.arbeidssokerperioder-v1"
hendelseloggTopic = "${HENDELSELOGG_TOPIC}"
hendelseStateStoreName = "hendelseState"