jvmMajorVersion=25
mavenRepo=paw-arbeidssoekerregisteret-monorepo-intern
chainguardJavaImage=europe-north1-docker.pkg.dev/cgr-nav/pull-through/nav.no/jre:openjdk-
avroSerializablePackages=no.nav.paw.arbeidssokerregisteret.api,no.nav.paw.bekreftelse.melding,no.nav.paw.bekreftelse.paavegneav,no.nav.person.pdl.aktor