apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-kafka-key-generator
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  port: 8080
  env:
    - name: PDL_URL
      value: "https://pdl-api.prod-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "api://prod-fss.pdl.pdl-api/.default"
    - name: PDL_TEMA
      value: "OPP"
    - name: KAFKA_TOPIC_PAW_HENDELSESLOGG
      value: "paw.arbeidssoker-hendelseslogg-v1"
    - name: KAFKA_CONSUMER_GROUP_ID_PREFIX_PAW_HENDELSESLOGG
      value: "paw-kafka-key-generator"
    - name: KAFKA_CONSUMER_GROUP_ID_VERSION_PAW_HENDELSESLOGG
      value: "1"
    - name: KAFKA_TOPIC_PAW_PERIODER
      value: "paw.arbeidssokerperioder-v1"
    - name: KAFKA_CONSUMER_GROUP_ID_PREFIX_PAW_PERIODER
      value: "paw-kafka-key-generator-paw-perioder"
    - name: KAFKA_CONSUMER_GROUP_ID_VERSION_PAW_PERIODER
      value: "1"
    - name: KAFKA_TOPIC_PDL_AKTOR
      value: "pdl.aktor-v2"
    - name: KAFKA_CONSUMER_GROUP_ID_PREFIX_PDL_AKTOR
      value: "paw-kafka-key-generator-pdl-aktor"
    - name: KAFKA_CONSUMER_GROUP_ID_VERSION_PDL_AKTOR
      value: "1"
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  kafka:
      pool: nav-prod
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-2-6144
        databases:
          - name: pawkafkakeys
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
      outbound:
        external:
          - host: pdl-api.prod-fss-pub.nais.io
      inbound:
        rules:
          - application: paw-brukerstotte
          - application: paw-microfrontend-toggler
          - application: paw-kafka-key-maintenance
          - application: paw-arbeidssokerregisteret-api-inngang
          - application: paw-arbeidssoekerregisteret-utgang-pdl
          - application: paw-arbeidssoekerregisteret-utgang-formidlingsgruppe
          - application: paw-arbeidssoekerregisteret-hendelselogg-backup
          - application: paw-arbeidssoekerregisteret-api-bekreftelse
          - application: paw-arbeidssoekerregisteret-bekreftelse-tjeneste
          - application: paw-arbeidssoekerregisteret-bekreftelse-backup
          - application: paw-arbeidssoekerregisteret-api-oppslag-v2
          - application: paw-arbeidssoekerregisteret-api-egenvurdering
          - application: dp-rapportering-personregister
            namespace: teamdagpenger
          - application: dp-rapportering
            namespace: teamdagpenger
          - application: flex-arbeidssokerregister-oppdatering
            namespace: flex
