apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-kafka-key-generator
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  port: 8080
  env:
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: PDL_SCOPE
      value: "api://dev-fss.pdl.pdl-api/.default"
    - name: PDL_TEMA
      value: "OPP"
    - name: KAFKA_CONSUMER_GROUP_ID
      value: "paw-kafka-key-generator-v1"
    - name: KAFKA_TOPIC_PAW_ARBEIDSSOKER_HENDELSESLOGG
      value: "paw.arbeidssoker-hendelseslogg-v1"
  ingresses:
    - https://record-key-arbeidssoekerregisteret.intern.dev.nav.no/api/v1/record-key
    - https://record-key-arbeidssoekerregisteret.intern.dev.nav.no/docs/record-key
  replicas:
    min: 2
    max: 2
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 20m
      memory: 256Mi
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  kafka:
      pool: nav-dev
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-custom-1-3840
        databases:
          - name: pawkafkakeys
  tokenx:
    enabled: true
  azure:
    application:
      enabled: true
  accessPolicy:
      outbound:
        external:
          - host: pdl-api.dev-fss-pub.nais.io
      inbound:
        rules:
          - application: azure-token-generator
            namespace: aura
          - application: paw-brukerstotte
          - application: paw-kafka-key-maintenance
          - application: paw-microfrontend-toggler
          - application: paw-arbeidssokerregisteret-api-inngang
          - application: paw-arbeidssoekerregisteret-utgang-pdl
          - application: paw-arbeidssoekerregisteret-utgang-formidlingsgruppe
          - application: paw-arbeidssoekerregisteret-hendelselogg-backup
          - application: paw-arbeidssoekerregisteret-api-bekreftelse
          - application: paw-arbeidssoekerregisteret-bekreftelse-tjeneste
          - application: paw-arbeidssoekerregisteret-bekreftelse-min-side-varsler
          - application: paw-arbeidssoekerregisteret-api-dolly
          - application: dp-rapportering-personregister
            namespace: teamdagpenger
          - application: dp-rapportering
            namespace: teamdagpenger
