eventLogTopic: paw.arbeidssoker-hendelseslogg-v1
poaoTilgangClientConfig:
  url: http://localhost:8090/poao-tilgang
  scope: api://test.test.poao-tilgang/.default
pdlClientConfig:
  url: http://localhost:8090/pdl
  scope: api://test.test.pdl-api/.default
kafkaKeysConfig:
  url: http://localhost:8090/kafka-keys
  urlLokalInfo: http://localhost:8090/kafka-keys/lokalinfo
  scope: api://test.test.kafka-keys/.default
authProviders:
  azure:
    name: azure
    discoveryUrl: http://localhost:8081/default/.well-known/openid-configuration
    tokenEndpointUrl: http://localhost:8081/default/token
    clientId: paw-arbeidssokerregisteret-api-inngang
    claims:
      - NAVident
  tokenx:
    name: tokenx
    discoveryUrl: http://localhost:8081/default/.well-known/openid-configuration
    tokenEndpointUrl: http://localhost:8081/default/token
    clientId: paw-arbeidssokerregisteret-api-inngang
    claims:
      - acr=Level4
      - acr=idporten-loa-high
