[bekreftelseIntervals]
interval = "${BEKREFTELSE_INTERVAL}"
graceperiode = "${BEKREFTELSE_GRACEPERIODE}"
tilgjengeligOffset = "${BEKREFTELSE_GRACEPERIODE}"

[kafkaTopology]
applicationIdSuffix = "${KAFKA_STREAMS_ID_SUFFIX}"
internStateStoreName = "intern-tilstand"
ansvarStateStoreName = "ansvar"
periodeTopic = "${KAFKA_PAW_ARBEIDSSOKERPERIODER_TOPIC}"
bekreftelseTopic = "${KAFKA_PAW_ARBEIDSSOKER_BEKREFTELSE_TOPIC}"
bekreftelseHendelseloggTopic = "${KAFKA_PAW_ARBEIDSSOKER_BEKREFTELSE_HENDELSELOGG_TOPIC}"
ansvarsTopic = "${KAFKA_PAW_ANSVARS_TOPIC}"
punctuationInterval = "${KAFKA_PUNCTUATOR_INTERVAL}"

[azureM2M]
tokenEndpointUrl = "${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}"
clientId = "${AZURE_APP_CLIENT_ID}"

[kafkaKeysClient]
url = "http://paw-kafka-key-generator/api/v2/hentEllerOpprett"
scope = "api://${NAIS_CLUSTER_NAME}.paw.paw-kafka-key-generator/.default"

[kafkaStreams]
brokers = "${KAFKA_BROKERS}"
applicationIdPrefix = "${KAFKA_STREAMS_APPLICATION_ID}"

[kafkaStreams.authentication]
keystorePath = "${KAFKA_KEYSTORE_PATH}"
truststorePath = "${KAFKA_TRUSTSTORE_PATH}"
credstorePassword = "${KAFKA_CREDSTORE_PASSWORD}"

[kafkaStreams.schemaRegistry]
url = "${KAFKA_SCHEMA_REGISTRY}"
username = "${KAFKA_SCHEMA_REGISTRY_USER}"
password = "${KAFKA_SCHEMA_REGISTRY_PASSWORD}"
