deaktiverUtmeldingVedStopp = "${DEAKTIVER_UTMELDING_VED_STOPP}"
[kafkaTopology]
applicationIdSuffix = "${KAFKA_STREAMS_ID_SUFFIX}"
internStateStoreName = "intern-tilstand"
bekreftelsePaaVegneAvStateStoreName = "paa-vegne-av-tilstand"
periodeTopic = "${KAFKA_PAW_ARBEIDSSOKERPERIODER_TOPIC}"
bekreftelseTopic = "${KAFKA_PAW_ARBEIDSSOKER_BEKREFTELSE_TOPIC}"
bekreftelseHendelseloggTopic = "${KAFKA_PAW_ARBEIDSSOKER_BEKREFTELSE_HENDELSELOGG_TOPIC}"
bekreftelsePaaVegneAvTopic = "${KAFKA_PAW_BEKREFTELSE_PAA_VEGNE_AV_TOPIC}"
punctuationInterval = "${KAFKA_PUNCTUATOR_INTERVAL}"

[azureM2M]
tokenEndpointUrl = "${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}"
clientId = "${AZURE_APP_CLIENT_ID}"

[kafkaKeysClient]
url = "http://paw-kafka-key-generator/api/v2/hentEllerOpprett"
urlLokalInfo = "http://paw-kafka-key-generator/api/v2/lokalInfo"
scope = "api://${NAIS_CLUSTER_NAME}.paw.paw-kafka-key-generator/.default"

[kafkaStreams]
brokers = "${KAFKA_BROKERS}"
applicationIdPrefix = "${KAFKA_STREAMS_APPLICATION_ID}"

[kafkaStreams.authentication]
keystorePath = "${KAFKA_KEYSTORE_PATH}"
truststorePath = "${KAFKA_TRUSTSTORE_PATH}"
credstorePassword = "${KAFKA_CREDSTORE_PASSWORD}"

[kafkaStreams.schemaRegistry]
url = "${KAFKA_SCHEMA_REGISTRY}"
username = "${KAFKA_SCHEMA_REGISTRY_USER}"
password = "${KAFKA_SCHEMA_REGISTRY_PASSWORD}"
