applicationIdSuffix = "v1"
producerId = "paw-bekreftelse-api"
bekreftelseTopic = "paw.bekreftelse-v1"
bekreftelseHendelseLoggTopic = "paw.bekreftelse-hendelse-logg-v1"
bekreftelseStateStoreName = "bekreftelseStateStore"
hostname = "${HOSTNAME}"

[[authProviders]]
name = "tokenx"
discoveryUrl = "${TOKEN_X_WELL_KNOWN_URL}"
tokenEndpointUrl = "${TOKEN_X_TOKEN_ENDPOINT}"
clientId = "${TOKEN_X_CLIENT_ID}"

[authProviders.claims]
map = ["acr=Level4", "acr=idporten-loa-high"]
combineWithOr = true

[[authProviders]]
name = "azure"
discoveryUrl = "${AZURE_APP_WELL_KNOWN_URL}"
tokenEndpointUrl = "${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}"
clientId = "${AZURE_APP_CLIENT_ID}"

[authProviders.claims]
map = ["NAVident"]

[kafkaKeyGeneratorClient]
url = "http://paw-kafka-key-generator/api/v2/hentEllerOpprett"
scope = "${KAFKA_KEYS_SCOPE}"

[poaoClientConfig]
url = "http://poao-tilgang.poao.svc.cluster.local"
scope = "api://${NAIS_CLUSTER_NAME}.poao.poao-tilgang/.default"