[[authProviders]]
name = "idporten"
clientId = "${IDPORTEN_CLIENT_ID}"
discoveryUrl = "${IDPORTEN_WELL_KNOWN_URL}

    [authProviders.claims]
    map = ["acr=idporten-loa-high"]

[[authProviders]]
name = "tokenx"
clientId = "${TOKEN_X_CLIENT_ID}"
discoveryUrl = "${TOKEN_X_WELL_KNOWN_URL}"

    [authProviders.claims]
    map = ["acr=Level4", "acr=idporten-loa-high"]
    combineWithOr = true

[[authProviders]]
name = "azure"
clientId = "${AZURE_APP_CLIENT_ID}"
discoveryUrl = "${AZURE_APP_WELL_KNOWN_URL}"

    [authProviders.claims]
    map = ["NAVident"]
