[[authProviders]]
name = "idporten"
audiences = ["${IDPORTEN_CLIENT_ID}"]
discoveryUrl = "${IDPORTEN_WELL_KNOWN_URL}

    [authProviders.requiredClaims]
    claims = ["acr=idporten-loa-high"]

[[authProviders]]
name = "tokenx"
audiences = ["${TOKEN_X_CLIENT_ID}"]
discoveryUrl = "${TOKEN_X_WELL_KNOWN_URL}"

    [authProviders.requiredClaims]
    claims = ["acr=Level4", "acr=idporten-loa-high"]
    combineWithOr = true

[[authProviders]]
name = "azure"
audiences = ["${AZURE_APP_CLIENT_ID}"]
discoveryUrl = "${AZURE_APP_WELL_KNOWN_URL}"

    [authProviders.requiredClaims]
    claims = ["NAVident"]
