eventLogTopic: paw.arbeidssoker-hendelseslogg-v1
poaoTilgangClientConfig:
  url: http://poao-tilgang.poao.svc.cluster.local
  scope: api://${NAIS_CLUSTER_NAME}.poao.poao-tilgang/.default
pdlClientConfig:
  url: ${PDL_URL}
  scope: ${PDL_SCOPE}
kafkaKeysConfig:
  url: http://paw-kafka-key-generator/api/v2/hentEllerOpprett
  scope: ${KAFKA_KEY_SCOPE}
authProviders:
  azure:
    name: azure
    discoveryUrl: ${AZURE_APP_WELL_KNOWN_URL}
    tokenEndpointUrl: ${AZURE_OPENID_CONFIG_TOKEN_ENDPOINT}
    clientId: ${AZURE_APP_CLIENT_ID}
    claims:
      - NAVident
  tokenx:
    name: tokenx
    discoveryUrl: ${TOKEN_X_WELL_KNOWN_URL}
    tokenEndpointUrl: ${TOKEN_X_TOKEN_ENDPOINT}
    clientId: ${TOKEN_X_CLIENT_ID}
    claims:
      - acr=Level4
      - acr=idporten-loa-high
