package no.nav.paw.arbeidssokerregisteret.application

const val MIDLERTIDIG_INTERNT_RESULTAT = -1

const val GODTATT = 0
const val AVVIST_PERSON_IKKE_FUNNET = 50
const val AVVIST_ALDER = 51
const val AVVIST_IKKE_BOSATT_I_NORGE_IHT_FOLKEREGISTERLOVEN = 52

const val AVVIST_UAVKLART = 100

const val IKKE_TILGANG = 150
const val IKKE_TILGANG_ANNEN_BRUKER = 151
const val IKKE_TILGANG_ANSATT_IKKE_TILGANG_TIL_BRUKER = 152
