syncFilePath = "/tmp/v1.csv"

[defaultVerdier]
periodeTilstand = "STARTET"
forhaandsgodkjentAvAnsatt = false

[apiInngang]
baseUrl = "http://localhost:8090"
scope = "api://test.paw.paw-arbeidssokerregisteret-api-inngang/.default"
