jobEnabled = true

syncFilePath = "/tmp/v1.csv"

[defaultVerdier]
periodeTilstand = "STOPPET"
forhaandsgodkjentAvAnsatt = false

[apiInngang]
baseUrl = "http://localhost:8090"
scope = "api://test.paw.paw-arbeidssokerregisteret-api-inngang/.default"
