apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-arbeidssoekerregisteret-hendelselogg-backup
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  ingresses:
    - https://intern-brukerstoette-arbeidssoekerregisteret.intern.nav.no
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
    initialDelay: 9000
  readiness:
    path: /internal/isReady
    initialDelay: 9000
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  kafka:
    pool: {{ kafka }}
  azure:
    application:
      enabled: true
      tenant: nav.no
      claims:
        extra:
          - NAVident
        groups:
          - id: 88b552ab-2cd9-41e1-bd44-3868605d6f6a
  env:
    - name: API_OPPSLAG_SCOPE
      value: "api://dev-gcp.paw.paw-arbeidssoekerregisteret-api-oppslag/.default"
    - name: KAFKA_KEYS_SCOPE
      value: "api://prod-gcp.paw.paw-kafka-key-generator/.default"
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 384Mi
      cpu: 40m
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: db-custom-1-6144
        databases:
          - name: hendelselogg