apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-arbeidssoekerregisteret-hendelselogg-backup
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  ingresses:
    - https://intern-brukerstoette-arbeidssoekerregisteret.intern.nav.no
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  kafka:
    pool: {{ kafka }}
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 384Mi
      cpu: 40m
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: db-custom-1-6144
        databases:
          - name: hendelselogg