### POST /api/v1/record-key

POST {{baseUrl}}/api/v1/proxy
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("azure")}}

{
    "method": "POST",
    "url": "http://paw-kafka-key-generator/api/v1/record-key",
    "body": {
        "ident": "01017012345"
    }
}

### POST /api/v2/hent

POST {{baseUrl}}/api/v1/proxy
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("azure")}}

{
    "method": "POST",
    "url": "http://paw-kafka-key-generator/api/v2/hent",
    "body": {
        "ident": "01017012345"
    }
}

### POST /api/v2/hentEllerOpprett

POST {{baseUrl}}/api/v1/proxy
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("azure")}}

{
    "method": "POST",
    "url": "http://paw-kafka-key-generator/api/v2/hentEllerOpprett",
    "body": {
        "ident": "01017012345"
    }
}

### POST /api/v2/identiteter

POST {{baseUrl}}/api/v1/proxy
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("azure")}}

{
    "method": "POST",
    "url": "http://paw-kafka-key-generator/api/v2/identiteter",
    "body": {
        "identitet": "01017012345"
    }
}