[bekreftelseKonfigurasjon]
migreringstidspunkt = "2020-01-06T23:00:00Z"
interval = "P14D"
graceperiode = "P7D"
tilgjengeligOffset = "P3D"

[kafkaTopology]
applicationIdSuffix = "v1"
internStateStoreName = "intern-tilstand"
ansvarStateStoreName = "ansvar"
periodeTopic = "paw.arbeidssokerperioder-v1"
bekreftelseTopic = "paw.arbeidssoker-bekreftelse-v1"
ansvarsTopic = "paw.arbeidssoker-bekreftelse-ansvar-v1"
bekreftelseHendelseloggTopic = "paw.arbeidssoker-bekreftelse-hendelseslogg-v1"
punctuationInterval = "PT5S"

[azureM2M]
tokenEndpointUrl = "http://localhost:8081/azure/token"
clientId = "paw-arbeidssoekerregisteret-bekreftelse-tjeneste"

[kafkaKeysClient]
url = "http://localhost:8081/api/v2/hentEllerOpprett"
scope = "api://local.paw.paw-kafka-key-generator/.default"

[kafkaStreams]
brokers = "localhost:9092"
applicationIdPrefix = "paw-arbeidssoekerregisteret-bekreftelse-tjeneste"

[kafkaStreams.schemaRegistry]
url = "http://localhost:8082"
