[kafkaTopology]
applicationIdSuffix = "v1"
internStateStoreName = "intern-tilstand"
bekreftelsePaaVegneAvStateStoreName = "paa-vegne-av-tilstand"
periodeTopic = "paw.arbeidssokerperioder-v1"
bekreftelseTopic = "paw.arbeidssoker-bekreftelse-v1"
bekreftelsePaaVegneAvTopic = "paw.arbeidssoker-bekreftelse-paavegneav-v1"
bekreftelseHendelseloggTopic = "paw.arbeidssoker-bekreftelse-hendelseslogg-v1"
punctuationInterval = "PT5S"

[azureM2M]
tokenEndpointUrl = "http://localhost:8081/azure/token"
clientId = "paw-arbeidssoekerregisteret-bekreftelse-tjeneste"

[kafkaKeysClient]
url = "http://localhost:8081/api/v2/hentEllerOpprett"
urlLokalInfo = "http://localhost:8081/api/v2/lokalInfo"
scope = "api://local.paw.paw-kafka-key-generator/.default"

[kafkaStreams]
brokers = "localhost:9092"
applicationIdPrefix = "paw-arbeidssoekerregisteret-bekreftelse-tjeneste"

[kafkaStreams.schemaRegistry]
url = "http://localhost:8082"
