[pawHendelseConsumer]
version = "${KAFKA_CONSUMER_GROUP_ID_VERSION_PAW_HENDELSESLOGG}"
topic = "${KAFKA_TOPIC_PAW_HENDELSESLOGG}"
groupIdPrefix = "${KAFKA_CONSUMER_GROUP_ID_PREFIX_PAW_HENDELSESLOGG}"

[pawPeriodeConsumer]
version = "${KAFKA_CONSUMER_GROUP_ID_VERSION_PAW_PERIODER}"
topic = "${KAFKA_TOPIC_PAW_PERIODER}"
groupIdPrefix = "${KAFKA_CONSUMER_GROUP_ID_PREFIX_PAW_PERIODER}"

[pdlAktorConsumer]
version = "${KAFKA_CONSUMER_GROUP_ID_VERSION_PDL_AKTOR}"
topic = "${KAFKA_TOPIC_PDL_AKTOR}"
groupIdPrefix = "${KAFKA_CONSUMER_GROUP_ID_PREFIX_PDL_AKTOR}"

[pawIdentitetProducer]
version = "${KAFKA_PRODUCER_CLIENT_ID_VERSION_PAW_IDENTITETER}"
topic = "${KAFKA_TOPIC_PAW_IDENTITETER}"
clientIdPrefix = "${KAFKA_PRODUCER_CLIENT_ID_PREFIX_PAW_IDENTITETER}"

[identitetKonfliktJob]
enabled = "${SCHEDULED_JOB_ENABLED_IDENTITET_KONFLIKT}"
delay = "${SCHEDULED_JOB_DELAY_IDENTITET_KONFLIKT}"
interval = "${SCHEDULED_JOB_INTERVAL_IDENTITET_KONFLIKT}"
batchSize = "${SCHEDULED_JOB_BATCH_SIZE_IDENTITET_KONFLIKT}"

[identitetHendelseJob]
enabled = "${SCHEDULED_JOB_ENABLED_IDENTITET_HENDELSE}"
delay = "${SCHEDULED_JOB_DELAY_IDENTITET_HENDELSE}"
interval = "${SCHEDULED_JOB_INTERVAL_IDENTITET_HENDELSE}"
batchSize = "${SCHEDULED_JOB_BATCH_SIZE_IDENTITET_HENDELSE}"