openapi: "3.0.3"
info:
  title: "paw_arbeidssokerregisteret_api_inngang API"
  description: "paw_arbeidssokerregisteret_api_inngang API"
  version: "1.0.0"
servers:
- url: "https://intern-brukerstoette-arbeidssoekerregisteret.intern.dev.nav.no"
  description: "Development environment"
- url: "https://intern-brukerstoette-arbeidssoekerregisteret.intern.nav.no"
  description: "Production environment"
paths:
  /api/v1/arbeidssoeker/detaljer:
    post:
      description: "Hent detaljer om bruker "
      parameters:
      - name: "traceparent"
        in: "header"
        required: false
        description: "https://www.w3.org/TR/trace-context/#traceparent-header-field-values"
        schema:
          type: "string"
          format: "traceparent"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DetaljerRequest"
        required: true
      responses:
        "400":
          description: "Bad Request"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feil"
        "500":
          description: "Internal Server Error"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feil"
        "403":
          description: "Forbidden"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feil"
        "200":
          description: "OK"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DetaljerResponse"

components:
  schemas:
    Feil:
      type: "object"
      properties:
        melding:
          type: "string"
        feilKode:
          type: "string"
      required:
      - "melding"
      - "feilKode"
    DetaljerRequest:
      type: "object"
      properties:
        identitetsnummer:
          type: "string"
          example: "12345678901"
      required:
      - "identitetsnummer"
    Tilstand:
      type: "object"
      properties:
        harAktivePeriode:
          type: "boolean"
          description: "Har aktiv periode"
          example: true
        periodeId:
          type: "string"
          format: "uuid"
          example: "123e4567-e89b-12d3-a456-426614174000"
          description: "Id for periode"
        startet:
          type: "string"
          format: "date-time"
          description: "Tidspunkt for start av periode"
          example: "2021-01-01T12:00:00Z"
        avsluttet:
          type: "string"
          format: "date-time"
          description: "Tidspunkt for avslutning av periode"
          example: "2021-01-02T12:00:00Z"
        harOpplysningerMottattHendelse:
          type: "boolean"
          description: "Har opplysninger"
          example: true
        gjeldeneOpplysningsId:
            type: "string"
            format: "uuid"
            example: "123e4567-e89b-12d3-a456-426614174000"
            description: "Id for gjeldene opplysninger for perioden, utelatt dersom ingen opplysninger er gitt"
        apiKall:
          type: "object"
          description: "Informasjons om resultatet av kall mot OpplsagsAPI, dersom ingen kall er gjort er dette feltet utelatt"
          properties:
            harPeriode:
              type: "boolean"
              description: "Har periode"
              example: true
            harOpplysning:
              type: "boolean"
              description: "Har opplysning"
              example: true
            harProfilering:
              type: "boolean"
              description: "Har profilerin"
              example: true
          required:
            - "harPeriode"
            - "harOpplysning"
            - "harProfilering"
      required:
        - "harAktivePeriode"
        - "startet"
        - "harOpplysningerMottattHendelse"
        - "periodeId"
    HendelseMetadata:
      type: "object"
      properties:
        tidspunkt:
          type: "string"
          format: "date-time"
          description: "Tidspunkt for hendelse"
          example: "2021-01-01T12:00:00Z"
        utfoertAv:
          type: "object"
          properties:
            type:
              type: "string"
              example: "System"
            id:
              type: "string"
              example: "Start stopp API: 1.0.0"
        kilde:
          type: "string"
          example: "Start stopp API"
        aarsak:
          type: "string"
          example: "Opplysninger mottatt fra bruker"
        tidspunktFraKilde:
          type: "object"
          properties:
            tidspunkt:
              type: "string"
              format: "date-time"
              description: "Tidspunkt for hendelse fra kilde"
              example: "2021-01-01T12:00:00Z"
            avvikstype:
              type: "string"
              example: "Avviks type"
          required:
            - "tidspunkt"
            - "avvikstype"
      required:
        - "tidspunkt"
        - "utfoertAv"
        - "kilde"
        - "aarsak"
    Hendelse:
      type: "object"
      properties:
        hendelseId:
          type: "string"
          format: "uuid"
          example: "123e4567-e89b-12d3-a456-426614174000"
        hendelseType:
          type: "string"
          description: "Type hendelse: Startet, Avsluttet, OpplysningerMottatt, Avvist"
          example: "Startet"
        metadata:
          $ref: "#/components/schemas/HendelseMetadata"
        kafkaPartition:
          type: "integer"
          format: "int32"
          description: "Kafka partition"
          example: 1
        kafkaOffset:
          type: "integer"
          format: "int64"
          description: "Kafka offset"
          example: 123234
        merged:
          type: "boolean"
          description: "Hendelsen stammer opprinnelig fra en annen arbeidssøker id"
          example: true
        api:
          type: "boolean"
          description: "Hendelsen finnes i API, bare inkludert dersom relevant"
          example: true
        data:
          type: "object"
          description: "Selve hendelsen"
      required:
        - "hendelseId"
        - "hendelseType"
        - "metadata"
        - "kafkaOffset"
        - "data"
    Snapshot:
      type: "object"
      properties:
        endret:
          type: "boolean"
          example: true
          description: "'true' indikerer at denne hendelsen har endret tilstanden til brukeren"
        gjeldeneTilstand:
          $ref: "#/components/schemas/Tilstand"
        nyTilstand:
          $ref: "#/components/schemas/Tilstand"
        hendelse:
          $ref: "#/components/schemas/Hendelse"
      required:
        - "hendelse"
        - "endret"

    DetaljerResponse:
      type: "object"
      properties:
        arbeidssoekerId:
          type: "integer"
          format: "int64"
          description: "Arbeidssøker id (intern id fra kafka keys"
          example: 123
        recordKey:
          type: "integer"
          format: "int64"
          description: "Record key brukt på kafka meldinger for denne personen"
        kafkaPartition:
          type: "integer"
          format: "int32"
          description: "Kafka partition"
          example: 1
        gjeldeneTilstand:
          $ref: "#/components/schemas/Tilstand"
        historikk:
          type: "array"
          items:
            $ref: "#/components/schemas/Snapshot"
      required:
        - "arbeidssoekId"
        - "recordKey"
        - "historikk"
