openapi: "3.0.3"
info:
  title: "paw_kafka_key_generator API"
  description: "paw_kafka_key_generator API"
  version: "1.0.0"
servers:
  - url: "https://paw_kafka_key_generator"
paths:
  /api/v2/info:
    post:
      operationId: postHentInfoV2
      description: "Hent info"
      parameters:
        - name: "traceparent"
          in: "header"
          required: false
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestV2"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InfoResponse"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "eea6958a-273d-4dbc-9c85-faaa37530cbf"
                type: "urn:paw:http:kunne-ikke-tolke-forespoersel"
                status: 400
                title: "Bad Request"
                detail: "Kunne ikke tolke forespørsel"
                instance: "/api/v2/info"
                timestamp: "2021-01-01T12:00:00.000Z"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "b88c0266-dd7f-40c1-9f8e-d7e511c36792"
                type: "urn:paw:default:ukjent-feil"
                status: 500
                title: "Internal Server Error"
                detail: "Ukjent feil"
                instance: "/api/v2/info"
                timestamp: "2021-01-01T12:00:00.000Z"
  /api/v2/hentEllerOpprett:
    post:
      operationId: postHentEllerOpprettKeyV2
      description: "Hent eller opprett Kafka keys"
      parameters:
        - name: "traceparent"
          in: "header"
          required: false
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestV2"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseV2"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "2854b631-e39c-48ff-975c-9e2195a0abc9"
                type: "urn:paw:http:kunne-ikke-tolke-forespoersel"
                status: 400
                title: "Bad Request"
                detail: "Kunne ikke tolke forespørsel"
                instance: "/api/v2/hentEllerOpprett"
                timestamp: "2021-01-01T12:00:00.000Z"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "9173d40e-6dd8-42e2-814a-ba5228cc4a41"
                type: "urn:paw:default:ukjent-feil"
                status: 500
                title: "Internal Server Error"
                detail: "Ukjent feil"
                instance: "/api/v2/hentEllerOpprett"
                timestamp: "2021-01-01T12:00:00.000Z"
  /api/v2/identiteter:
    post:
      operationId: postIdentiteter
      description: "Finn ideniteter"
      parameters:
        - name: "traceparent"
          in: "header"
          required: false
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IdentitetRequest"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IdentitetResponse"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "3cd944fb-6187-41a8-91b2-b172f2baf890"
                type: "urn:paw:http:kunne-ikke-tolke-forespoersel"
                status: 400
                title: "Bad Request"
                detail: "Kunne ikke tolke forespørsel"
                instance: "/api/v2/identiteter"
                timestamp: "2021-01-01T12:00:00.000Z"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "896a8d1e-8e76-445a-bb62-5e37971e3410"
                type: "urn:paw:default:ukjent-feil"
                status: 500
                title: "Internal Server Error"
                detail: "Ukjent feil"
                instance: "/api/v2/identiteter"
                timestamp: "2021-01-01T12:00:00.000Z"
  /internal/isAlive:
    get:
      operationId: getIsAlive
      description: "Service is alive probe"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
        "503":
          description: "Service Unavailable"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
  /internal/isReady:
    get:
      operationId: getIsReady
      description: "Service is ready probe"
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
        "503":
          description: "Service Unavailable"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
  /internal/metrics:
    get:
      operationId: getMetrics
      description: "Prometheus metrics"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
components:
  schemas:
    InfoResponse:
      type: "object"
      properties:
        info:
          $ref: "#/components/schemas/Info"
        mergeDetected:
          type: "object"
          properties:
            id:
              type: "object"
              properties:
                value:
                  type: "string"
            map:
              type: "object"
              additionalProperties: true
    Info:
      type: "object"
      properties:
        identitetsnummer:
          type: "string"
        lagretData:
          type: "object"
          properties:
            arbeidssoekerId:
              type: "integer"
              format: "int64"
            recordKey:
              type: "integer"
              format: "int64"
        pdlData:
          type: "object"
          properties:
            error:
              type: "string"
            id:
              type: "array"
              items:
                type: "string"
    RequestV2:
      type: "object"
      properties:
        ident:
          type: "string"
      required:
        - "ident"
      example:
        ident: "01017012345"
    ResponseV2:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        key:
          type: "integer"
          format: "int64"
      required:
        - id
        - key
      example:
        id: 1234
        key: -1234
    IdentitetRequest:
      type: "object"
      properties:
        identitet:
          type: "string"
      required:
        - "identitet"
      example:
        identitet: "01017012345"
    IdentitetResponse:
      type: "object"
      properties:
        arbeidssoekerId:
          type: "integer"
          format: "int64"
        recordKey:
          type: "integer"
          format: "int64"
        identiteter:
          type: "array"
          items:
            $ref: "#/components/schemas/Identitet"
        pdlIdentiteter:
          type: "array"
          items:
            $ref: "#/components/schemas/Identitet"
        konflikter:
          type: "array"
          items:
            $ref: "#/components/schemas/Konflikt"
      required:
        - "identiteter"
      example:
        arbeidssoekerId: 10170
        recordKey: 170
        identiteter:
          - identitet: "200001017012345"
            type: "AKTORID"
            gjeldende: true
          - identitet: "2010170"
            type: "ARBEIDSSOEKERID"
            gjeldende: true
          - identitet: "01017012345"
            type: "FOLKEREGISTERIDENT"
            gjeldende: true
    Identitet:
      type: "object"
      properties:
        identitet:
          type: "string"
        type:
          $ref: "#/components/schemas/IdentitetType"
        gjeldende:
          type: "boolean"
      required:
        - identitet
        - type
        - gjeldende
      example:
        identitet: "01017012345"
        type: "FOLKEREGISTERIDENT"
        gjeldende: true
    IdentitetType:
      type: "string"
      enum:
        - "FOLKEREGISTERIDENT"
        - "AKTORID"
        - "NPID"
        - "ARBEIDSSOEKERID"
        - "UKJENT_VERDI"
    Konflikt:
      type: object
      properties:
        type:
          $ref: "#/components/schemas/KonfliktType"
        detaljer:
          $ref: "#/components/schemas/KonfliktDetaljer"
      required:
        - type
    KonfliktDetaljer:
      type: object
      properties:
        aktorIdListe:
          type: "array"
          items:
            type: "string"
        arbeidssoekerIdListe:
          type: "array"
          items:
            type: "integer"
            format: "int64"
      required:
        - aktorIdListe
        - arbeidssoekerIdListe
    KonfliktType:
      type: "string"
      enum:
        - "MERGE"
        - "SPLITT"
        - "SLETT"
    ProblemDetails:
      type: object
      properties:
        id:
          type: "string"
          format: "uuid"
        type:
          type: "string"
          format: "uri"
        status:
          type: "integer"
        title:
          type: "string"
        detail:
          type: "string"
        instance:
          type: "string"
        timestamp:
          type: "string"
          format: "date-time"
      required:
        - id
        - type
        - status
        - title
        - detail
        - instance
        - timestamp
      example:
        id: "3cd944fb-6187-41a8-91b2-b172f2baf890"
        type: "urn:paw:default:ukjent-feil"
        status: 500
        title: "Internal Server Error"
        detail: "Ukjent feil"
        instance: "/api/v2/info"
        timestamp: "2021-01-01T12:00:00.000Z"
    HealthStatus:
      type: "string"
      enum:
        - "UNKNOWN"
        - "HEALTHY"
        - "UNHEALTHY"
