openapi: "3.0.3"
info:
  title: "paw_kafka_key_generator API"
  description: "paw_kafka_key_generator API"
  version: "1.0.0"
servers:
  - url: "https://paw_kafka_key_generator"
paths:
  /api/v2/info:
    post:
      operationId: postHentInfoV2
      description: "Hent info"
      parameters:
        - name: "traceparent"
          in: "header"
          required: false
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestV2"
        required: true
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/InfoResponse"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "3cd944fb-6187-41a8-91b2-b172f2baf890"
                type: "urn:paw:http:kunne-ikke-tolke-forespoersel"
                status: 400
                title: "Bad Request"
                detail: "Kunne ikke tolke forespørsel"
                instance: "/api/v2/info"
                timestamp: "2021-01-01T12:00:00.000Z"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "3cd944fb-6187-41a8-91b2-b172f2baf890"
                type: "urn:paw:default:ukjent-feil"
                status: 500
                title: "Internal Server Error"
                detail: "Ukjent feil"
                instance: "/api/v2/info"
                timestamp: "2021-01-01T12:00:00.000Z"
  /api/v2/hentEllerOpprett:
    post:
      operationId: postHentEllerOpprettKeyV2
      description: "Hent eller opprett Kafka keys"
      parameters:
        - name: "traceparent"
          in: "header"
          required: false
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestV2"
        required: true
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseV2"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "3cd944fb-6187-41a8-91b2-b172f2baf890"
                type: "urn:paw:http:kunne-ikke-tolke-forespoersel"
                status: 400
                title: "Bad Request"
                detail: "Kunne ikke tolke forespørsel"
                instance: "/api/v2/hentEllerOpprett"
                timestamp: "2021-01-01T12:00:00.000Z"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "3cd944fb-6187-41a8-91b2-b172f2baf890"
                type: "urn:paw:default:ukjent-feil"
                status: 500
                title: "Internal Server Error"
                detail: "Ukjent feil"
                instance: "/api/v2/hentEllerOpprett"
                timestamp: "2021-01-01T12:00:00.000Z"
  /internal/isAlive:
    get:
      operationId: getIsAlive
      description: "Service is alive probe"
      responses:
        "503":
          description: "Service Unavailable"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
  /internal/isReady:
    get:
      operationId: getIsReady
      description: "Service is ready probe"
      responses:
        "503":
          description: "Service Unavailable"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
  /internal/metrics:
    get:
      operationId: getMetrics
      description: "Prometheus metrics"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: "string"
components:
  schemas:
    InfoResponse:
      type: "object"
      properties:
        info:
          $ref: "#/components/schemas/Info"
        mergeDetected:
          type: "object"
          properties:
            id:
              type: "object"
              properties:
                value:
                  type: "string"
            map:
              type: "object"
              additionalProperties: true
    Info:
      type: "object"
      properties:
        identitetsnummer:
          type: "string"
        lagretData:
          type: "object"
          properties:
            arbeidssoekerId:
              type: "integer"
              format: "int64"
            recordKey:
              type: "integer"
              format: "int64"
        pdlData:
          type: "object"
          properties:
            error:
              type: "string"
            id:
              type: "array"
              items:
                type: "string"
    RequestV2:
      type: "object"
      properties:
        ident:
          type: "string"
      required:
        - "ident"
      example:
        ident: "01017012345"
    ResponseV2:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        key:
          type: "integer"
          format: "int64"
      example:
        id: 1234
        key: -1234
    ProblemDetails:
      type: object
      properties:
        id:
          type: "string"
          format: "uuid"
        type:
          type: "string"
          format: "uri"
        status:
          type: "integer"
        title:
          type: "string"
        detail:
          type: "string"
        instance:
          type: "string"
      required:
        - id
        - type
        - status
        - title
        - detail
        - instance
      example:
        id: "3cd944fb-6187-41a8-91b2-b172f2baf890"
        type: "urn:paw:default:ukjent-feil"
        status: 500
        title: "Internal Server Error"
        detail: "Ukjent feil"
        instance: "/api/v2/info"
        timestamp: "2021-01-01T12:00:00.000Z"
    HealthStatus:
      type: "string"
      enum:
        - "UNKNOWN"
        - "HEALTHY"
        - "UNHEALTHY"
