openapi: "3.0.3"
info:
  title: "paw_kafka_key_generator Oppslag API"
  description: "Read only API"
  version: "1.0.0"
servers:
  - url: "https://paw_kafka_key_generator"
  - url: "https://record-key-arbeidssoekerregisteret.intern.dev.nav.no"
    description: "Dev"
paths:
  /api/v1/record-key:
    post:
      description: ""
      parameters:
        - name: "traceparent"
          in: "header"
          required: false
          description: "https://www.w3.org/TR/trace-context/#traceparent-header-field-values"
          schema:
            type: "string"
            format: "traceparent"
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/RecordKeyLookupRequestV1"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponseV1"
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/FailureResponseV1"
        "200":
          description: ""
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/RecordKeyLookupResponseV1"
components:
  schemas:
    RecordKeyLookupRequestV1:
      type: "object"
      properties:
        ident:
          type: "string"
      required:
      - "ident"
    RecordKeyLookupResponseV1:
      type: "object"
      properties:
        key:
          type: "integer"
          format: "int64"
    FailureResponseV1:
        type: "object"
        properties:
            message:
              type: "string"
            code:
              type: "string"
              enum:
                - "UKJENT_REGISTERET"
                - "UKJENT_IDENT"
        required:
        - "message"
