openapi: "3.0.3"
info:
  title: "paw_kafka_key_generator Oppslag API"
  description: "Read only API"
  version: "1.0.0"
servers:
  - url: "https://paw_kafka_key_generator"
  - url: "https://record-key-arbeidssoekerregisteret.intern.dev.nav.no"
    description: "Dev"
paths:
  /api/v1/record-key:
    post:
      description: "Hent Record Key"
      parameters:
        - name: "traceparent"
          in: "header"
          required: false
          description: "https://www.w3.org/TR/trace-context/#traceparent-header-field-values"
          schema:
            type: "string"
            format: "traceparent"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RecordKeyLookupRequestV1"
        required: true
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RecordKeyLookupResponseV1"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
components:
  schemas:
    RecordKeyLookupRequestV1:
      type: "object"
      properties:
        ident:
          type: "string"
      required:
      - "ident"
    RecordKeyLookupResponseV1:
      type: "object"
      properties:
        key:
          type: "integer"
          format: "int64"
    ProblemDetails:
      type: object
      properties:
        id:
          type: "string"
          format: "uuid"
        type:
          type: "string"
          format: "uri"
        status:
          type: "integer"
        title:
          type: "string"
        detail:
          type: "string"
        instance:
          type: "string"
        timestamp:
          type: "string"
          format: "date-time"
      required:
        - id
        - type
        - status
        - title
        - detail
        - instance
        - timestamp
      example:
        id: "3cd944fb-6187-41a8-91b2-b172f2baf890"
        type: "urn:paw:default:ukjent-feil"
        status: 500
        title: "Internal Server Error"
        detail: "Ukjent feil"
        instance: "/api/v2/info"
        timestamp: "2021-01-01T12:00:00.000Z"
