varselProducerId = "${NAIS_APP_NAME}-varsel-producer-v1"
periodeStreamSuffix = "${KAFKA_PERIODE_STREAM_SUFFIX}"
bekreftelseStreamSuffix = "${KAFKA_BEKREFTELSE_STREAM_SUFFIX}"
varselHendelseStreamSuffix = "${KAFKA_VARSEL_HENDELSE_STREAM_SUFFIX}"
periodeTopic = "${KAFKA_PAW_ARBEIDSOKERPERIODE_TOPIC}"
bekreftelseHendelseTopic = "${KAFKA_PAW_ARBEIDSOKER_BEKREFTELSE_HENDELSESLOGG_TOPIC}"
tmsVarselTopic = "${KAFKA_TMS_AAPEN_BRUKERVARSEL_TOPIC}"
tmsVarselHendelseTopic = "${KAFKA_TMS_AAPEN_VARSEL_HENDELSE_TOPIC}"
manueltVarselEnabled = "${MANUELT_VARSEL_ENABLED}"
manueltVarselSchedulingDelay = "PT10M"
manueltVarselSchedulingInterval = "PT10M"
oppryddingEnabled = "${OPPRYDDING_ENABLED}"
oppryddingSchedulingDelay = "PT1H"
oppryddingSchedulingInterval = "PT6H"
oppryddingEldreEnn = "P30D"
