periodeAvsluttet:
  link: ${PERIODE_AVSLUTTET_VARSEL_LINK}
  sensitivitet: SUBSTANTIAL
  standardSpraak:
    kode: nb
  tekster:
    - spraak:
        kode: nb
      tekst: Du er ikke lenger registrert som arbeidssøker.
    - spraak:
        kode: nn
      tekst: Du er ikke lenger registrert som arbeidssøker. [nn]
    - spraak:
        kode: en
      tekst: You are no longer registered as job seeker
  eksterntVarsel:
    preferertKanal: BETINGET_SMS
    smsTekst: Du er ikke lengre registrert som arbeidssøker. Hilsen Nav
    epostTittel: Du har fått en melding fra Nav
    epostTekst: <html><body><p>Hei!</p><p>Du er ikke lengre registrert som arbeidssøker.</p><p>Hilsen Nav</p></body></html>

bekreftelseTilgjengelig:
  link: ${BEKREFTELSE_TILGJENGELIG_VARSEL_LINK}
  sensitivitet: SUBSTANTIAL
  standardSpraak:
    kode: nb
  tekster:
    - spraak:
        kode: nb
      tekst: Bekreft at du vil være registrert som arbeidssøker.
    - spraak:
        kode: nn
      tekst: Bekreft at du vil være registrert som arbeidssøker. [nn]
    - spraak:
        kode: en
      tekst: Bekreft at du vil være registrert som arbeidssøker. [en]
  eksterntVarsel:
    preferertKanal: BETINGET_SMS
    smsTekst: Hei! Ønsker du fortsatt å være registrert som arbeidssøker? Logg inn på Nav så snart som mulig for å bekrefte at du vil være registrert. Hilsen Nav
    epostTittel: Du har fått en melding fra Nav
    epostTekst: <html><body><p>Hei!</p><p>Ønsker du fortsatt å være registrert som arbeidssøker hos Nav? Logg inn på Nav så snart som mulig for å bekrefte at du vil være registrert som arbeidssøker.</p><p>Hilsen Nav</p></body></html>

manueltVarsel:
  link: ${MANUELT_VARSEL_LINK}
  sensitivitet: SUBSTANTIAL
  standardSpraak:
    kode: nb
  tekster:
    - spraak:
        kode: nb
      tekst: Endring i meldekort for arbeidssøkere fra 20. mars.
    - spraak:
        kode: nn
      tekst: Endring i meldekort for arbeidssøkere fra 20. mars. [nn]
    - spraak:
        kode: en
      tekst: Endring i meldekort for arbeidssøkere fra 20. mars. [en]
