periodeAvsluttet:
  link: ${PERIODE_AVSLUTTET_VARSEL_LINK}
  sensitivitet: SUBSTANTIAL
  standardSpraak:
    kode: nb
  tekster:
    - spraak:
        kode: nb
      tekst: Arbeidssøkerperioden ble avsluttet hos NAV.
    - spraak:
        kode: en
      tekst: Your jobseeker period was ended at NAV.
  eksterntVarsel:
    prefererteKanaler:
      - SMS
      - EPOST

bekreftelseTilgjengelig:
  link: ${BEKREFTELSE_TILGJENGELIG_VARSEL_LINK}
  sensitivitet: SUBSTANTIAL
  standardSpraak:
    kode: nb
  tekster:
    - spraak:
        kode: nb
      tekst: Bekreft at du vil være registrert som arbeidssøker.
    - spraak:
        kode: en
      tekst: Confirm that you want to remain a jobseeker.
  eksterntVarsel:
    prefererteKanaler:
      - SMS
      - EPOST
    smsTekst: Hei! Ønsker du fortsatt å være registrert som arbeidssøker? Logg inn på Nav så snart som mulig for å bekrefte at du vil være registrert. Hilsen Nav
    epostTittel: Du har fått en melding fra Nav
    epostTekst: Hei!\nØnsker du fortsatt å være registrert som arbeidssøker hos Nav? Logg inn på Nav så snart som mulig for å bekrefte at du vil være registrert som arbeidssøker.\nHilsen Nav

manueltVarsel:
  link: ${MANUELT_VARSEL_LINK}
  sensitivitet: SUBSTANTIAL
  standardSpraak:
    kode: nb
  tekster:
    - spraak:
        kode: nb
      tekst: Dette er en test av manuelt varsel fra NAV.
    - spraak:
        kode: en
      tekst: This is a test of a manual notification from NAV.
