periodeAvsluttet:
  link: ${PERIODE_AVSLUTTET_VARSEL_LINK}
  sensitivitet: SUBSTANTIAL
  standardSpraak:
    kode: nb
  tekster:
    - spraak:
        kode: nb
      tekst: Du er ikke lenger registrert som arbeidssøker
    - spraak:
        kode: nn
      tekst: Du er ikkje lenger registrert som arbeidssøkjar
    - spraak:
        kode: en
      tekst: You are no longer registered as a job seeker
  eksterntVarsel:
    preferertKanal: BETINGET_SMS
    smsTekst: Hei! Du er ikke lenger registrert som arbeidssøker hos Nav. Logg inn på Nav hvis du vil vite hva dette betyr for deg. Hilsen Nav
    epostTittel: Du har fått en melding fra Nav
    epostTekst: Hei!<br>Du er ikke lenger registrert som arbeidssøker hos Nav. Logg inn på Nav hvis du vil vite hva dette betyr for deg.<br>Hilsen Nav

bekreftelseTilgjengelig:
  link: ${BEKREFTELSE_TILGJENGELIG_VARSEL_LINK}
  sensitivitet: SUBSTANTIAL
  standardSpraak:
    kode: nb
  tekster:
    - spraak:
        kode: nb
      tekst: Bekreft at du vil være registrert som arbeidssøker hos Nav
    - spraak:
        kode: nn
      tekst: Stadfest at du vil vera registrert som arbeidssøkjar hos Nav
    - spraak:
        kode: en
      tekst: Confirm that you want to be registered as a jobseeker with Nav
  eksterntVarsel:
    preferertKanal: BETINGET_SMS
    smsTekst: Hei! Ønsker du fortsatt å være registrert som arbeidssøker? Logg inn på Nav for å bekrefte at du vil være registrert. Hilsen Nav
    epostTittel: Du har fått en melding fra Nav
    epostTekst: Hei!<br>Ønsker du fortsatt å være registrert som arbeidssøker? Logg inn på Nav for å bekrefte at du vil være registrert.<br>Hilsen Nav

manueltVarsel:
  link: ${MANUELT_VARSEL_LINK}
  sensitivitet: SUBSTANTIAL
  standardSpraak:
    kode: nb
  tekster:
    - spraak:
        kode: nb
      tekst: Endringer for deg som sender meldekort fra 20. mars
    - spraak:
        kode: nn
      tekst: Endring i meldekort for arbeidssøkjarar frå 20. mars
    - spraak:
        kode: en
      tekst: Changes in employment status form for job seekers from March 20th
