[streamKonfigurasjon]
tilstandsDatabase = "tilstand-beta-v6"
applikasjonsId = "${KAFKA_STREAMS_APPLICATION_ID}-beta-v6"
eventlogTopic = "paw.arbeidssoker-hendelseslogg-beta-v6"
periodeTopic = "paw.arbeidssokerperioder-beta-v6"
opplysningerOmArbeidssoekerTopic = "paw.opplysninger-om-arbeidssoeker-beta-v6"

[serverKonfigurasjon]
autentisering = "SSL"
kafkaBrokers = "${KAFKA_BROKERS}"
kafkaSchemaRegistry = "${KAFKA_SCHEMA_REGISTRY}"
keystorePath = "${KAFKA_KEYSTORE_PATH}"
credstorePassword = "${KAFKA_CREDSTORE_PASSWORD}"
truststorePath = "${KAFKA_TRUSTSTORE_PATH}"

[schemaRegistryKonfigurasjon]
url = "${KAFKA_SCHEMA_REGISTRY}"
bruker = "${KAFKA_SCHEMA_REGISTRY_USER}"
passord = "${KAFKA_SCHEMA_REGISTRY_PASSWORD}"
