apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-arbeidssoekerregisteret-utgang-formidlingsgruppe
  namespace: paw
  labels:
    team: paw
spec:
  azure:
    application:
      enabled: true
  image: {{ image }}
  port: 8080
  replicas:
    min: 6
    max: 6
  env:
    - name: KAFKA_KEYS_SCOPE
      value: api://prod-gcp.paw.paw-kafka-key-generator/.default
    - name: HENDELSELOGG_TOPIC
      value: "paw.arbeidssoker-hendelseslogg-v1"
    - name: APPLICATION_STREAM_VERSION
      value: "v6"
  liveness:
    path: /isAlive
    initialDelay: 10
  readiness:
    path: /isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  kafka:
    pool: {{ kafka }}
    streams: true
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 1024Mi
      cpu: 250m
  accessPolicy:
    outbound:
      rules:
        - application: paw-kafka-key-generator
