[kafkaTopology]
bekreftelseTargetTopic = "${KAFKA_BEKREFTELSE_TARGET_TOPIC}"
bekreftelsePaaVegneAvTargetTopic = "${KAFKA_BEKREFTELSE_PAAVEGNEAV_TARGET_TOPIC}"

[[bekreftelseKlienter]]
versjon = 2
bekreftelsesloesning = "dagpenger"
paaVegneAvSourceTopic = "${KAFKA_TEAMDAGPENGER_BEKREFTELSE_PAAVEGNEAV_SOURCE_TOPIC}"
bekreftelseSourceTopic = "${KAFKA_TEAMDAGPENGER_BEKREFTELSE_SOURCE_TOPIC}"

[[bekreftelseKlienter]]
versjon = 1
bekreftelsesloesning = "friskmeldt_til_arbeidsformidling"
paaVegneAvSourceTopic = "${KAFKA_FRISKMELDT_TIL_ARBEIDSFORMIDLING_BEKREFTELSE_PAAVEGNEAV_SOURCE_TOPIC}"
bekreftelseSourceTopic = "${KAFKA_FRISKMELDT_TIL_ARBEIDSFORMIDLING_BEKREFTELSE_SOURCE_TOPIC}"
