openapi: "3.0.3"
info:
  title: "paw_arbeidssokerregisteret_bekreftelse_backup brukerstoette API"
  description: "paw_arbeidssokerregisteret_bekreftelse_backup brukerstoette API"
  version: "1.0.0"
servers:
- url: "https://brukerstoette-arbeidssoekerregisteret-bekreftelse.intern.dev.nav.no"
  description: "Development environment"
- url: "https://brukerstoette-arbeidssoekerregisteret-bekreftelse.intern.nav.no"
  description: "Production environment"
paths:
  /api/v1/arbeidssoeker/bekreftelse-hendelser:
    post:
      description: "Hent bekreftelse-hendelser knyttet til bruker "
      parameters:
      - name: "traceparent"
        in: "header"
        required: false
        description: "https://www.w3.org/TR/trace-context/#traceparent-header-field-values"
        schema:
          type: "string"
          format: "traceparent"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/HendelserRequest"
        required: true
      responses:
        "400":
          description: "Bad Request"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feil"
        "500":
          description: "Internal Server Error"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feil"
        "403":
          description: "Forbidden"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Feil"
        "200":
          description: "OK"
          headers:
            x-trace-id:
              description: "Trace id"
              schema:
                type: "string"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BekreftelseHendelserResponse"

components:
  schemas:
    Feil:
      type: "object"
      properties:
        melding:
          type: "string"
        feilKode:
          type: "string"
      required:
      - "melding"
      - "feilKode"
    HendelserRequest:
      type: "object"
      properties:
        identitetsnummer:
          type: "string"
          example: "12345678901"
      required:
      - "identitetsnummer"
    BekreftelseHendelserResponse:
      type: "array"
      items:
        $ref: "#/components/schemas/Hendelse"
    Hendelse:
      type: "object"
      properties:
        hendelseId:
          type: "string"
          format: "uuid"
          example: "123e4567-e89b-12d3-a456-426614174000"
        hendelseType:
          type: "string"
          description: "Type hendelse: BekreftelseTilgjengelig, BekreftelseMeldingMottatt, BaOmAaAvsluttePeriode, BekreftelsePaaVegneAvStartet, LeveringsfristUtloept, RegisterGracePeriodeGjenstaaendeTid, RegisterGracePeriodeUtloept, RegisterGracePeriodeUtloeptEtterEksternInnsamling, BekreftelseMeldingMottatt"
          example: "Startet"
        hendelseTidspunkt:
          type: "string"
          format: "date-time"
          example: "2021-01-01T12:00:00Z"
        periodeId:
          type: "string"
          format: "uuid"
          example: "123e4567-e89b-12d3-a456-426614174000"
        kafkaPartition:
          type: "integer"
          format: "int32"
          description: "Kafka partition"
          example: 1
        kafkaOffset:
          type: "integer"
          format: "int64"
          description: "Kafka offset"
          example: 123234
        data:
          type: "object"
          description: "Selve hendelsen"
      required:
        - "hendelseId"
        - "hendelseType"
        - "hendelseTidspunkt"
        - "periodeId"
        - "kafkaPartition"
        - "kafkaOffset"
        - "data"
