apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-arbeidssoekerregisteret-bekreftelse-min-side-varsler
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  port: 8080
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 256Mi
      cpu: 25m
  env:
    - name: KAFKA_BEKREFTELSE_STREAM_SUFFIX
      value: bekreftelse-beta-v3
    - name: KAFKA_VARSEL_HENDELSE_STREAM_SUFFIX
      value: varsel-hendelser-beta-v3
    - name: KAFKA_PAW_ARBEIDSOKERPERIODE_TOPIC
      value: paw.arbeidssokerperioder-v1
    - name: KAFKA_PAW_ARBEIDSOKER_BEKREFTELSE_HENDELSESLOGG_TOPIC
      value: paw.arbeidssoker-bekreftelse-hendelseslogg-beta-v2
    - name: KAFKA_TMS_AAPEN_BRUKERVARSEL_TOPIC
      value: min-side.aapen-brukervarsel-v1
    - name: KAFKA_TMS_AAPEN_VARSEL_HENDELSE_TOPIC
      value: min-side.aapen-varsel-hendelse-v1
    - name: KAFKA_KEYS_SCOPE
      value: api://dev-gcp.paw.paw-kafka-key-generator/.default
    - name: VARSEL_LINK
      value: https://www.ansatt.dev.nav.no/arbeidssoekerregisteret/bekreftelse
  liveness:
    path: /internal/isAlive
    initialDelay: 10
  readiness:
    path: /internal/isReady
    initialDelay: 10
  azure:
    application:
      enabled: true
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  kafka:
    pool: {{ kafka }}
    streams: true
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        tier: db-f1-micro
        databases:
          - name: pawbekreftelseminsideoppgaver
  accessPolicy:
    outbound:
      rules:
        - application: paw-kafka-key-generator
