[kafkaTopology]
version = 1
antallPartitioner = 6
producerId = "${NAIS_APP_NAME}-v1-producer"
consumerId = "${NAIS_APP_NAME}-v1-consumer"
consumerGroupId = "${NAIS_APP_NAME}-v1"
hendelsesloggTopic = "${HENDELSESLOGG_TOPIC}"