jobEnabled = "${JOB_ENABLED}"

[csvFil]
filsti = "/var/run/secrets/paw-arbeidssoekere-synk-jobb-csv/v6.csv"
kolonneSeparator = ";"
innholderHeader = false
inneholderKommentarer = false

[defaultVerdier]
periodeTilstand = "STARTET" # STARTET / STOPPET
forhaandsgodkjentAvAnsatt = true
# Verdiene under benyttes kun om CSV-rad inneholder tidspunkt
feilrettingFeiltype = "FEIL_TIDSPUNKT" # FEIL_TIDSPUNKT / FEIL_REGISTRERING
feilrettingMelding = "Arbeidssøker migrert fra Arena"

[apiInngang]
baseUrl = "http://paw-arbeidssokerregisteret-api-inngang"
scope = "api://${NAIS_CLUSTER_NAME}.paw.paw-arbeidssokerregisteret-api-inngang/.default"
