syncFilePath = "/var/run/secrets/paw-arbeidssoekere-synk-jobb-csv/v1.csv"

[defaultVerdier]
periodeTilstand = "STARTET"
forhaandsgodkjentAvAnsatt = false

[apiInngang]
baseUrl = "http://paw-arbeidssokerregisteret-api-inngang"
scope = "api://${NAIS_CLUSTER_NAME}.paw.paw-arbeidssokerregisteret-api-inngang/.default"
