jobEnabled = "${JOB_ENABLED}"

syncFilePath = "/var/run/secrets/paw-arbeidssoekere-synk-jobb-csv/v2.csv"

[defaultVerdier]
periodeTilstand = "STOPPET"
forhaandsgodkjentAvAnsatt = false

[apiInngang]
baseUrl = "http://paw-arbeidssokerregisteret-api-inngang"
scope = "api://${NAIS_CLUSTER_NAME}.paw.paw-arbeidssokerregisteret-api-inngang/.default"
