syncFilePath = "/var/run/secrets/paw-arbeidssoekere-synk-jobb-csv/v1.csv"
markerForhaandsgodkjentAvAnsatt = false
apiInngangBaseUrl = "http://paw-arbeidssokerregisteret-api-inngang"
apiInngangScope = "api://${NAIS_CLUSTER_NAME}.paw.paw-arbeidssokerregisteret-api-inngang/.default"
