eventLogTopic: arbeidssokerperiode-start-v1
poaoTilgangClientConfig:
  url: http://localhost:8090/poao-tilgang
  scope: api://test.test.poao-tilgang/.default
pdlClientConfig:
  url: http://localhost:8090/pdl
  scope: api://test.test.pdl-api/.default
kafkaKeysConfig:
  url: ${KAFKA_KEYS_URL}
  scope: ${KAFKA_KEYS_SCOPE}
authProviders:
  azure:
    name: azure
    discoveryUrl: ${AZURE_APP_WELL_KNOWN_URL}
    tokenEndpointUrl: http://localhost:8081/default/token
    clientId: paw-arbeidssokerregisteret-api-inngang
    claims:
      - NAVident
  tokenx:
    name: tokenx
    discoveryUrl: http://localhost:8081/default/.well-known/openid-configuration
    tokenEndpointUrl: http://localhost:8081/default/token
    clientId: paw-arbeidssokerregisteret-api-inngang
    claims:
      - acr=Level4
      - acr=idporten-loa-high
