bekreftelseStreamSuffix = "${KAFKA_BEKREFTELSE_STREAM_SUFFIX}"
varselHendelseStreamSuffix = "${KAFKA_VARSEL_HENDELSE_STREAM_SUFFIX}"
periodeTopic="${KAFKA_PAW_ARBEIDSOKERPERIODE_TOPIC}"
bekreftelseHendelseTopic="${KAFKA_PAW_ARBEIDSOKER_BEKREFTELSE_HENDELSESLOGG_TOPIC}"
tmsVarselTopic="${KAFKA_TMS_AAPEN_BRUKERVARSEL_TOPIC}"
tmsVarselHendelseTopic="${KAFKA_TMS_AAPEN_VARSEL_HENDELSE_TOPIC}"
skalSendeVarsler = false
