openapi: "3.0.3"
info:
  title: "paw_arbeidssokerregisteret_api_dolly API"
  description: "API mot arbeidssoekerregisteret i DEV. Brukes for å registrere testperson som arbeidssøker ved opprettelse av testpersoner i Dolly. Felter som ikke er utfylt erstattes med standardverdier."
  version: "1.0.0"
servers:
  - url: "http://dev-gcp.paw-arbeidssoekerregisteret-api-dolly.paw"
    description: "Development"
paths:
  /api/v1/arbeidssoekerregistrering/{identitetsnummer}:
    get:
      operationId: "getArbeidssoekerregistrering"
      description: "Henter arbeidssøkerregistrering for identitetsnummer"
      parameters:
        - name: "identitetsnummer"
          in: "path"
          required: true
          schema:
            $ref: "#/components/schemas/Identitetsnummer"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ArbeidssoekerregistreringResponse"
              example:
                identitetsnummer: "12345678901"
                utfoertAv: "SYSTEM"
                kilde: "Dolly"
                aarsak: "Registrerer testbruker i dev"
                nuskode: "4"
                utdanningBestaatt: true
                utdanningGodkjent: true
                jobbsituasjonsbeskrivelse: "HAR_SAGT_OPP"
                jobbsituasjonsdetaljer:
                  gjelderFraDato: "2021-01-01"
                  gjelderTilDato: "2021-01-31"
                  stillingStyrk08: "00"
                  stillingstittel: "Butikkmedarbeider"
                  stillingsprosent: "100"
                  sisteDagMedLoenn: "2021-01-31"
                  sisteArbeidsdag: "2021-01-31"
                helsetilstandHindrerArbeid: false
                andreForholdHindrerArbeid: false
                registreringstidspunkt: "2021-01-01T12:00:00Z"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "fa85c6aa-29a8-4378-bff7-7cbc4a1e9b5a"
                type: "urn:paw:ressurs-ikke-funnet"
                status: 404
                title: "Not Found"
                detail: "Ressurs ikke funnet"
                instance: "/api/v1/arbeidssoekerregistrering/12345678901"
                timestamp: "2021-01-01T12:00:00.000Z"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "fa85c6aa-29a8-4378-bff7-7cbc4a1e9b5a"
                type: "urn:paw:http:kunne-ikke-tolke-forespoersel"
                status: 400
                title: "Bad Request"
                detail: "Identitetsnummer må bestå av 11 sifre"
                instance: "/api/v1/arbeidssoekerregistrering/1234"
                timestamp: "2021-01-01T12:00:00.000Z"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "fa85c6aa-29a8-4378-bff7-7cbc4a1e9b5a"
                type: "urn:paw:default:ukjent-feil"
                status: 500
                title: "Internal Server Error"
                detail: "Ukjent feil"
                instance: "/api/v1/arbeidssoekerregistrering/12345678911"
                timestamp: "2021-01-01T12:00:00.000Z"
    delete:
      operationId: "deleteArbeidssoekerregistrering"
      description: "Avslutter brukers arbeidssøkerperiode"
      parameters:
        - name: "identitetsnummer"
          in: "path"
          required: true
          schema:
            $ref: "#/components/schemas/Identitetsnummer"
      responses:
        "204":
          description: "No Content"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "fa85c6aa-29a8-4378-bff7-7cbc4a1e9b5a"
                type: "urn:paw:ressurs-ikke-funnet"
                status: 404
                title: "Not Found"
                detail: "Ressurs ikke funnet"
                instance: "/api/v1/arbeidssoekerregistrering/12345678901"
                timestamp: "2021-01-01T12:00:00.000Z"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "fa85c6aa-29a8-4378-bff7-7cbc4a1e9b5a"
                type: "urn:paw:default:ukjent-feil"
                status: 500
                title: "Internal Server Error"
                detail: "Ukjent feil"
                instance: "/api/v1/arbeidssoekerregistrering/1234"
                timestamp: "2021-01-01T12:00:00.000Z"

  /api/v1/arbeidssoekerregistrering:
    post:
      operationId: "postArbeidssoekerregistrering"
      description: "Registrerer bruker som arbeidssøker"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ArbeidssoekerregistreringRequest"
      responses:
        "202":
          description: "Accepted"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "fa85c6aa-29a8-4378-bff7-7cbc4a1e9b5a"
                type: "urn:paw:http:kunne-ikke-tolke-forespoersel"
                status: 400
                title: "Bad Request"
                detail: "Kunne ikke tolke forespørsel"
                instance: "/api/v1/arbeidssoekerregistrering"
                timestamp: "2021-01-01T12:00:00.000Z"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "fa85c6aa-29a8-4378-bff7-7cbc4a1e9b5a"
                type: "urn:paw:default:ukjent-feil"
                status: 500
                title: "Internal Server Error"
                detail: "Ukjent feil"
                instance: "/api/v1/arbeidssoekerregistrering"
                timestamp: "2021-01-01T12:00:00.000Z"

  /api/v1/typer/{type}:
    get:
      operationId: "getType"
      description: "Returnerer liste av objekter hvor key er enum verdi og value er enum beskrivelse"
      parameters:
        - name: "type"
          in: "path"
          required: true
          schema:
            $ref: "#/components/schemas/TypeRequest"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/TypeResponse"
        "404":
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "fa85c6aa-29a8-4378-bff7-7cbc4a1e9b5a"
                type: "urn:paw:ressurs-ikke-funnet"
                status: 404
                title: "Not Found"
                detail: "Ressurs ikke funnet"
                instance: "/api/v1/typer/UKJENT"
                timestamp: "2021-01-01T12:00:00.000Z"
        "400":
          description: "Bad Request"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "fa85c6aa-29a8-4378-bff7-7cbc4a1e9b5a"
                type: "urn:paw:http:kunne-ikke-tolke-forespoersel"
                status: 400
                title: "Bad Request"
                detail: "Type må være JOBBSITUASJONSBESKRIVELSE eller BRUKERTYPE"
                instance: "/api/v1/typer/UKJENT"
                timestamp: "2021-01-01T12:00:00.000Z"
        "500":
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ProblemDetails"
              example:
                id: "fa85c6aa-29a8-4378-bff7-7cbc4a1e9b5a"
                type: "urn:paw:default:ukjent-feil"
                status: 500
                title: "Internal Server Error"
                detail: "Ukjent feil"
                instance: "/api/v1/typer"
                timestamp: "2021-01-01T12:00:00.000Z"

  /internal/isAlive:
    get:
      operationId: "getIsAlive"
      description: "Service is alive probe"
      responses:
        "503":
          description: "Service Unavailable"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
              example:
                "UNHEALTHY"
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
              example:
                "HEALTHY"
  /internal/isReady:
    get:
      operationId: "getIsReady"
      description: "Service is ready probe"
      responses:
        "503":
          description: "Service Unavailable"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
              example:
                "UNHEALTHY"
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                $ref: "#/components/schemas/HealthStatus"
              example:
                "HEALTHY"

components:
  schemas:
    Identitetsnummer:
      type: "string"
      pattern: "^[0-9]{11}$"
      description: "Fødselsnummer eller D-nummer"

    ArbeidssoekerregistreringRequest:
      type: "object"
      properties:
        identitetsnummer:
          $ref: "#/components/schemas/Identitetsnummer"
        utfoertAv:
          $ref: "#/components/schemas/Brukertype"
        kilde:
          type: "string"
          example: "Dolly"
        aarsak:
          type: "string"
          example: "Registrerer testbruker i dev"
        nuskode:
          type: "string"
          example: "4"
        utdanningBestaatt:
          type: "boolean"
        utdanningGodkjent:
          type: "boolean"
        jobbsituasjonsbeskrivelse:
          $ref: "#/components/schemas/Jobbsituasjonsbeskrivelse"
        jobbsituasjonsdetaljer:
          $ref: "#/components/schemas/Jobbsituasjonsdetaljer"
        helsetilstandHindrerArbeid:
          type: "boolean"
        andreForholdHindrerArbeid:
          type: "boolean"
      required:
        - "identitetsnummer"

    ArbeidssoekerregistreringResponse:
      type: "object"
      properties:
        identitetsnummer:
          $ref: "#/components/schemas/Identitetsnummer"
        utfoertAv:
          $ref: "#/components/schemas/Brukertype"
        kilde:
          type: "string"
        aarsak:
          type: "string"
        nuskode:
          type: "string"
        utdanningBestaatt:
          type: "boolean"
        utdanningGodkjent:
          type: "boolean"
        jobbsituasjonsbeskrivelse:
          $ref: "#/components/schemas/Jobbsituasjonsbeskrivelse"
        jobbsituasjonsdetaljer:
          $ref: "#/components/schemas/Jobbsituasjonsdetaljer"
        helsetilstandHindrerArbeid:
          type: "boolean"
        andreForholdHindrerArbeid:
          type: "boolean"
        registreringstidspunkt:
          type: "string"
          format: "date-time"
          example: "2021-01-01T12:00:00Z"
      required:
        - "identitetsnummer"
        - "utfoertAv"
        - "kilde"
        - "aarsak"
        - "nuskode"
        - "jobbsituasjonsbeskrivelse"
        - "jobbsituasjonsdetaljer"
        - "helsetilstandHindrerArbeid"
        - "andreForholdHindrerArbeid"
        - "registreringstidspunkt"

    TypeRequest:
      type: "string"
      enum:
        - "JOBBSITUASJONSBESKRIVELSE"
        - "BRUKERTYPE"
        - "NUSKODE"

    TypeResponse:
      type: array
      items:
        type: object
        properties:
          key:
            type: string
          value:
            type: string
        example:
          key: "UKJENT_VERDI"
          value: "Ukjent verdi"
      example:
        - key: "UKJENT_VERDI"
          value: "Ukjent verdi"
        - key: "UDEFINERT"
          value: "Udefinert"
        - key: "HAR_SAGT_OPP"
          value: "Har sagt opp jobben"
        - key: "HAR_BLITT_SAGT_OPP"
          value: "Har blitt sagt opp"
        - key: "ER_PERMITTERT"
          value: "Er permittert"
        - key: "ALDRI_HATT_JOBB"
          value: "Har aldri hatt jobb"
        - key: "IKKE_VAERT_I_JOBB_SISTE_2_AAR"
          value: "Ikke vært i jobb siste 2 år"
        - key: "AKKURAT_FULLFORT_UTDANNING"
          value: "Har akkurat fullført utdanning"
        - key: "VIL_BYTTE_JOBB"
          value: "Vil bytte jobb"
        - key: "USIKKER_JOBBSITUASJON"
          value: "Usikker jobbsituasjon"
        - key: "MIDLERTIDIG_JOBB"
          value: "Har midlertidig jobb"
        - key: "DELTIDSJOBB_VIL_MER"
          value: "Har deltidsjobb, vil ha mer"
        - key: "NY_JOBB"
          value: "Har fått ny jobb"
        - key: "KONKURS"
          value: "Har gått konkurs"
        - key: "ANNET"
          value: "Annet"

    Brukertype:
      type: "string"
      enum:
        - "UKJENT_VERDI"
        - "UDEFINERT"
        - "VEILEDER"
        - "SYSTEM"
        - "SLUTTBRUKER"

    Jobbsituasjonsbeskrivelse:
      type: "string"
      enum:
        - "UKJENT_VERDI"
        - "UDEFINERT"
        - "HAR_SAGT_OPP"
        - "HAR_BLITT_SAGT_OPP"
        - "ER_PERMITTERT"
        - "ALDRI_HATT_JOBB"
        - "IKKE_VAERT_I_JOBB_SISTE_2_AAR"
        - "AKKURAT_FULLFORT_UTDANNING"
        - "VIL_BYTTE_JOBB"
        - "USIKKER_JOBBSITUASJON"
        - "MIDLERTIDIG_JOBB"
        - "DELTIDSJOBB_VIL_MER"
        - "NY_JOBB"
        - "KONKURS"
        - "ANNET"

    Nuskode:
      type: "string"
      enum:
        - "0"
        - "1"
        - "2"
        - "3"
        - "4"
        - "5"
        - "6"
        - "7"
        - "8"

    Jobbsituasjonsdetaljer:
      type: "object"
      properties:
        gjelderFraDato:
          type: "string"
          format: "date"
        gjelderTilDato:
          type: "string"
          format: "date"
        stillingStyrk08:
          type: "string"
          pattern: "^[0-9]{1,4}$"
          example: "00"
        stillingstittel:
          type: "string"
          example: "Butikkmedarbeider"
        stillingsprosent:
          type: "string"
          pattern: "^[0-9]{1,3}$"
        sisteDagMedLoenn:
          type: "string"
          format: "date"
        sisteArbeidsdag:
          type: "string"
          format: "date"

    ProblemDetails:
      type: "object"
      properties:
        id:
          type: "string"
          format: "uuid"
        type:
          type: "string"
          format: "uri"
        status:
          type: "integer"
        title:
          type: "string"
        detail:
          type: "string"
        instance:
          type: "string"
        timestamp:
          type: "string"
          format: "date-time"
          example: "2021-01-01T12:00:00Z"
      required:
        - "id"
        - "type"
        - "status"
        - "title"
        - "detail"
        - "instance"
        - "timestamp"

    HealthStatus:
      type: "string"
      enum:
        - "UNKNOWN"
        - "HEALTHY"
        - "UNHEALTHY"
