openapi: "3.0.3"
info:
  title: "paw_arbeidssokerregisteret_api_dolly API"
  description: "API mot arbeidssoekerregisteret i DEV. Brukes for å automatisk registrere person som arbeidssøker ved opprettelse av testpersoner i Dolly. For felter som ikke er utfylt vil defaultverdier bli satt."
  version: "1.0.0"
servers:
  - url: "https://dolly-arbeidssoekerregisteret.intern.dev.nav.no"
    description: "Development"
paths:
  /api/v1/arbeidssoekerregistrering:
    post:
      description: "Registrerer bruker som arbeidssøker"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ArbeidssoekerregistreringRequest"
      responses:
        "400":
          description: "Bad Request"
          content:
            text/plain:
              schema:
                type: "string"
        "500":
          description: "Internal Server Error"
          content:
            text/plain:
              schema:
                type: "string"
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"

components:
  schemas:
    Identitetsnummer:
      type: "string"
      pattern: "^[0-9]{11}$"
      description: "Fødselsnummer eller D-nummer"
    ArbeidssoekerregistreringRequest:
      type: "object"
      properties:
        identitetsnummer:
          $ref: "#/components/schemas/Identitetsnummer"
        utfoertAv:
          $ref: "#/components/schemas/BrukerType"
        kilde:
          type: "string"
          example: "Dolly"
        aarsak:
          type: "string"
          example: "Registrerer testbruker i dev"
        nuskode:
          type: "string"
          example: "4"
        utdanningBestaatt:
          type: "boolean"
        utdanningGodkjent:
          type: "boolean"
        jobbsituasjonBeskrivelse:
          $ref: "#/components/schemas/Beskrivelse"
        jobbsituasjonDetaljer:
          $ref: "#/components/schemas/Detaljer"
        helsetilstandHindrerArbeid:
          type: "boolean"
        andreForholdHindrerArbeid:
          type: "boolean"
      required:
        - "identitetsnummer"

    BrukerType:
      type: "string"
      enum:
        - "UKJENT_VERDI"
        - "UDEFINERT"
        - "VEILEDER"
        - "SYSTEM"
        - "SLUTTBRUKER"

    Beskrivelse:
      type: "string"
      enum:
        - "UKJENT_VERDI"
        - "UDEFINERT"
        - "HAR_SAGT_OPP"
        - "HAR_BLITT_SAGT_OPP"
        - "ER_PERMITTERT"
        - "ALDRI_HATT_JOBB"
        - "IKKE_VAERT_I_JOBB_SISTE_2_AAR"
        - "AKKURAT_FULLFORT_UTDANNING"
        - "VIL_BYTTE_JOBB"
        - "USIKKER_JOBBSITUASJON"
        - "MIDLERTIDIG_JOBB"
        - "DELTIDSJOBB_VIL_MER"
        - "NY_JOBB"
        - "KONKURS"
        - "ANNET"

    Detaljer:
      type: "object"
      properties:
        gjelder_fra_dato_iso8601:
          type: "string"
          format: "date"
        gjelder_til_dato_iso8601:
          type: "string"
          format: "date"
        stilling_styrk08:
          type: "string"
          pattern: "^[0-9]{1,4}$"
          example: "00"
        stilling:
          type: "string"
          example: "Butikkmedarbeider"
        prosent:
          type: "string"
          pattern: "^[0-9]{1,3}$"
        siste_dag_med_loenn_iso8601:
          type: "string"
          format: "date"
        siste_arbeidsdag_iso8601:
          type: "string"
          format: "date"
