package no.nav.paw.arbeidssoeker.synk.model

import java.time.Instant

data class OpprettPeriodeRequest(
    val identitetsnummer: String,
    val periodeTilstand: PeriodeTilstand,
    val registreringForhaandsGodkjentAvAnsatt: Boolean? = null,
    val feilretting: Feilretting? = null
)

enum class PeriodeTilstand(val value: String) {
    STARTET("STARTET"),
    STOPPET("STOPPET");
}

data class Feilretting(
    val feilType: FeilType,
    val melding: String? = null,
    val tidspunkt: Instant? = null
)

enum class FeilType(val value: String) {
    FeilTidspunkt("FeilTidspunkt"),
    Feilregistrering("Feilregistrering");
}

data class OpprettPeriodeErrorResponse(
    val melding: String,
    val feilKode: FeilKode,
    val aarsakTilAvvisning: AarsakTilAvvisning? = null
)

enum class FeilKode(val value: String) {
    UKJENT_FEIL("UKJENT_FEIL"),
    UVENTET_FEIL_MOT_EKSTERN_TJENESTE("UVENTET_FEIL_MOT_EKSTERN_TJENESTE"),
    FEIL_VED_LESING_AV_FORESPORSEL("FEIL_VED_LESING_AV_FORESPORSEL"),
    AVVIST("AVVIST"),
    IKKE_TILGANG("IKKE_TILGANG");
}

data class AarsakTilAvvisning(
    val detaljer: List<AvvisningDetaljer>,
    val regler: List<AvvisningRegel>? = null
)

enum class AvvisningDetaljer(val value: String) {
    FORHAANDSGODKJENT_AV_ANSATT("FORHAANDSGODKJENT_AV_ANSATT"),
    SAMME_SOM_INNLOGGET_BRUKER("SAMME_SOM_INNLOGGET_BRUKER"),
    IKKE_SAMME_SOM_INNLOGGER_BRUKER("IKKE_SAMME_SOM_INNLOGGER_BRUKER"),
    ANSATT_IKKE_TILGANG("ANSATT_IKKE_TILGANG"),
    ANSATT_TILGANG("ANSATT_TILGANG"),
    IKKE_ANSATT("IKKE_ANSATT"),
    ER_OVER_18_AAR("ER_OVER_18_AAR"),
    ER_UNDER_18_AAR("ER_UNDER_18_AAR"),
    UKJENT_FOEDSELSDATO("UKJENT_FOEDSELSDATO"),
    UKJENT_FOEDSELSAAR("UKJENT_FOEDSELSAAR"),
    TOKENX_PID_IKKE_FUNNET("TOKENX_PID_IKKE_FUNNET"),
    OPPHOERT_IDENTITET("OPPHOERT_IDENTITET"),
    IKKE_BOSATT("IKKE_BOSATT"),
    DOED("DOED"),
    SAVNET("SAVNET"),
    HAR_NORSK_ADRESSE("HAR_NORSK_ADRESSE"),
    HAR_UTENLANDSK_ADRESSE("HAR_UTENLANDSK_ADRESSE"),
    INGEN_ADRESSE_FUNNET("INGEN_ADRESSE_FUNNET"),
    BOSATT_ETTER_FREG_LOVEN("BOSATT_ETTER_FREG_LOVEN"),
    DNUMMER("DNUMMER"),
    UKJENT_FORENKLET_FREG_STATUS("UKJENT_FORENKLET_FREG_STATUS"),
    HAR_GYLDIG_OPPHOLDSTILLATELSE("HAR_GYLDIG_OPPHOLDSTILLATELSE"),
    OPPHOLDSTILATELSE_UTGAATT("OPPHOLDSTILATELSE_UTGAATT"),
    BARN_FOEDT_I_NORGE_UTEN_OPPHOLDSTILLATELSE("BARN_FOEDT_I_NORGE_UTEN_OPPHOLDSTILLATELSE"),
    INGEN_INFORMASJON_OM_OPPHOLDSTILLATELSE("INGEN_INFORMASJON_OM_OPPHOLDSTILLATELSE"),
    UKJENT_STATUS_FOR_OPPHOLDSTILLATELSE("UKJENT_STATUS_FOR_OPPHOLDSTILLATELSE"),
    PERSON_IKKE_FUNNET("PERSON_IKKE_FUNNET"),
    SISTE_FLYTTING_VAR_UT_AV_NORGE("SISTE_FLYTTING_VAR_UT_AV_NORGE"),
    SISTE_FLYTTING_VAR_INN_TIL_NORGE("SISTE_FLYTTING_VAR_INN_TIL_NORGE"),
    IKKE_MULIG_AA_IDENTIFISERE_SISTE_FLYTTING("IKKE_MULIG_AA_IDENTIFISERE_SISTE_FLYTTING"),
    INGEN_FLYTTE_INFORMASJON("INGEN_FLYTTE_INFORMASJON"),
    ER_GBR_STATSBORGER("ER_GBR_STATSBORGER"),
    ER_EU_EOES_STATSBORGER("ER_EU_EOES_STATSBORGER"),
    ER_NORSK_STATSBORGER("ER_NORSK_STATSBORGER"),
    HAR_REGISTRERT_ADRESSE_I_EU_EOES("HAR_REGISTRERT_ADRESSE_I_EU_EOES"),
    UKJENT_OPPLYSNING("UKJENT_OPPLYSNING"),
    ER_FEILRETTING("ER_FEILRETTING"),
    UGYLDIG_FEILRETTING("UGYLDIG_FEILRETTING");
}

data class AvvisningRegel(
    val id: AvvisningRegelId? = null,
    val beskrivelse: String? = null
)

enum class AvvisningRegelId(val value: String) {
    UKJENT_REGEL("UKJENT_REGEL"),
    IKKE_FUNNET("IKKE_FUNNET"),
    SAVNET("SAVNET"),
    DOED("DOED"),
    OPPHOERT_IDENTITET("OPPHOERT_IDENTITET"),
    ENDRE_FOR_ANNEN_BRUKER("ENDRE_FOR_ANNEN_BRUKER"),
    ANSATT_IKKE_TILGANG_TIL_BRUKER("ANSATT_IKKE_TILGANG_TIL_BRUKER"),
    IKKE_TILGANG("IKKE_TILGANG"),
    UNDER_18_AAR("UNDER_18_AAR"),
    IKKE_BOSATT_I_NORGE_I_HENHOLD_TIL_FOLKEREGISTERLOVEN("IKKE_BOSATT_I_NORGE_I_HENHOLD_TIL_FOLKEREGISTERLOVEN"),
    ER_EU_EOES_STATSBORGER_MED_STATUS_IKKE_BOSATT("ER_EU_EOES_STATSBORGER_MED_STATUS_IKKE_BOSATT"),
    UKJENT_ALDER("UKJENT_ALDER");
}
