apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-arbeidssoekerregisteret-utgang-pdl
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  env:
    - name: KAFKA_KEYS_SCOPE
      value: api://dev-gcp.paw.paw-kafka-key-generator/.default
    - name: PDL_SCOPE
      value: "api://dev-fss.pdl.pdl-api/.default"
    - name: PDL_URL
      value: "https://pdl-api.dev-fss-pub.nais.io/graphql"
    - name: HENDELSELOGG_TOPIC
      value: "paw.arbeidssoker-hendelseslogg-v1"
  azure:
    application:
      enabled: true
  kafka:
    pool: nav-dev
    streams: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 3500m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 1024Mi
  liveness:
    path: /isAlive
    initialDelay: 10
  readiness:
    path: /isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /metrics
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  accessPolicy:
    outbound:
      rules:
        - application: paw-kafka-key-generator
      external:
        - host: pdl-api.dev-fss-pub.nais.io
