apiVersion: v1
kind: ConfigMap
metadata:
  name: paw-connect-{{topic}}
  namespace: paw
  labels:
    team: paw
    destination: connect
    enabled: "true"
spec:
  kafka:
    pool: nav-dev
data:
  data.json: |-
    {
      "name": "{{topic}}",
      "config": {
        "connector.class": "com.wepay.kafka.connect.bigquery.BigQuerySinkConnector",
        "autoCreateTables": "true",
        "sanitizeTopics": "true",
        "topics": "paw.{{topic}}",
        "tasks.max": "1",
        "project": "{{project}}",
        "defaultDataset": "paw_dataprodukter_kafka",
        "transforms": "dropPrefix",
        "transforms.dropPrefix.type": "org.apache.kafka.connect.transforms.RegexRouter",
        "transforms.dropPrefix.regex": "paw\\.(.*)",
        "transforms.dropPrefix.replacement": "$1",
        "allowBigQueryRequiredFieldRelaxation": "true",
        "allowNewBigQueryFields": "true",
        "value.converter.value.subject.name.strategy": "io.confluent.kafka.serializers.subject.RecordNameStrategy",
        "value.converter.schema.registry.url": "$(KAFKA_SCHEMA_REGISTRY)",
        "value.converter.basic.auth.credentials.source": "USER_INFO",
        "value.converter.basic.auth.user.info": "$(KAFKA_SCHEMA_REGISTRY_USER):$(KAFKA_SCHEMA_REGISTRY_PASSWORD)",
        "value.converter": "io.confluent.connect.avro.AvroConverter",
      }
    }
