apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: paw-arbeidssokerregisteret-event-prosessor
  namespace: paw
  labels:
    team: paw
spec:
  image: {{ image }}
  port: 8080
  env:
    - name: OTEL_METRICS_EXPORTER
      value: "none"
    - name: OTEL_TRACES_EXPORTER
      value: "maskert_oltp"
    - name: OTEL_JAVAAGENT_DEBUG
      value: "false"
  replicas:
    min: 1
    max: 1
  liveness:
    path: /isAlive
    initialDelay: 10
  readiness:
    path: /isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /metrics
  observability:
    tracing:
      enabled: true
  kafka:
    pool: {{ kafka }}
    streams: true
  replicas:
    cpuThresholdPercentage: 50
    disableAutoScaling: true
    max: 1
    min: 1
  resources:
    limits:
      cpu: 500m
      memory: 3072Mi
    requests:
      cpu: 200m
      memory: 2048Mi
