[streamKonfigurasjon]
tilstandsDatabase = "tilstand"
applikasjonsId = "appId"
eventlogTopic = "paw.arbeidssoker-hendelseslogg-v1"
periodeTopic = "paw.arbeidssokerperioder-v1"
opplysningerOmArbeidssoekerTopic = "paw.opplysninger-om-arbeidssoeker-v1"

[serverKonfigurasjon]
autentisering = "PLAIN"
kafkaBrokers = "localhost:9092"

[schemaRegistryKonfigurasjon]
url = "http://localhost:8082"
