[streamKonfigurasjon]
tilstandsDatabase = "tilstand"
applikasjonsId = "appId"
eventlogTopic = "hendelselogg-v1"
periodeTopic = "periode-v1"
opplysningerOmArbeidssoekerTopic = "opplysninger-om-arbeidssoeker-v1"

[serverKonfigurasjon]
autentisering = "PLAIN"
kafkaBrokers = "localhost:9092"

[schemaRegistryKonfigurasjon]
url = "http://localhost:8082"
