url="http://paw-arbeidssoekerregisteret-api-oppslag"
scope="${API_OPPSLAG_SCOPE}"
perioderPath="/api/v1/veileder/arbeidssoekerperioder"
opplysningerPath="/api/v1/veileder/opplysninger-om-arbeidssoeker"
profileringPath="/api/v1/veileder/profilering"
