host = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_HENDELSELOGG_BACKUP_HENDELSELOGG_HOST}"
port = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_HENDELSELOGG_BACKUP_HENDELSELOGG_PORT}"
username = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_HENDELSELOGG_BACKUP_HENDELSELOGG_USERNAME}"
password = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_HENDELSELOGG_BACKUP_HENDELSELOGG_PASSWORD}"
database = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_HENDELSELOGG_BACKUP_HENDELSELOGG_DATABASE}"
jdbcUrl = "${NAIS_DATABASE_PAW_ARBEIDSSOEKERREGISTERET_HENDELSELOGG_BACKUP_HENDELSELOGG_JDBC_URL}"
