# Signering-nøkkel-indeks — nøkkel-id til ressurssti for offentlige nøkler
# Mappenavn = nøkkel-id som settes i x-paw-signing-key-id-headeren
paw-api-inngang-kafka-signing-key=signing-keys/paw-api-inngang-kafka-signing-key/paw-api-inngang-kafka-sining-key-v2.dev.pub.b64
paw-api-inngang-kafka-signing-key-v2=signing-keys/paw-api-inngang-kafka-signing-key-v2/paw-api-inngang-kafka-signing-key-v2.dev.pub.b64
