[autorisasjon]
corsAllowOrigins = "localhost"

[kafkaTopology]
version = 1
antallPartitioner = 1
producerId = "paw-arbeidssoekerregisteret-api-bekreftelse-v1-producer"
consumerId = "paw-arbeidssoekerregisteret-api-bekreftelse-v1-consumer"
consumerGroupId = "paw-arbeidssoekerregisteret-api-bekreftelse-v1"
bekreftelseTopic = "paw.arbeidssoker-bekreftelse-v1"
bekreftelseHendelsesloggTopic = "paw.arbeidssoker-bekreftelse-hendelseslogg-v1"
