[[authProviders]]
name = "idporten"
audiences = ["paw-arbeidssoekerregisteret-api-bekreftelse"]
discoveryUrl = "http://localhost:8081/idporten/.well-known/openid-configuration"

    [authProviders.requiredClaims]
    claims = [
        "acr=idporten-loa-substantial", # == Level3
        "acr=idporten-loa-high" # == Level4
    ]

[[authProviders]]
name = "tokenx"
audiences = ["paw-arbeidssoekerregisteret-api-bekreftelse"]
discoveryUrl = "http://localhost:8081/tokenx/.well-known/openid-configuration"

    [authProviders.requiredClaims]
    claims = [
        "acr=Level3",
        "acr=Level4",
        "acr=idporten-loa-substantial", # == Level3
        "acr=idporten-loa-high" # == Level4
    ]
    combineWithOr = true

[[authProviders]]
name = "azure"
audiences = ["paw-arbeidssoekerregisteret-api-bekreftelse"]
discoveryUrl = "http://localhost:8081/azure/.well-known/openid-configuration"

    [authProviders.requiredClaims]
    claims = ["NAVident"]
