package no.nav.paw.arbeidssokerregisteret.app.config.nais

const val KAFKA_BROKER_URL = "KAFKA_BROKER_URL"

const val KAFKA_BROKERS = "KAFKA_BROKERS"

const val KAFKA_SCHEMA_REGISTRY = "KAFKA_SCHEMA_REGISTRY"

const val KAFKA_SCHEMA_REGISTRY_USER = "KAFKA_SCHEMA_REGISTRY_USER"

const val KAFKA_SCHEMA_REGISTRY_PASSWORD = "KAFKA_SCHEMA_REGISTRY_PASSWORD"

const val KAFKA_CERTIFICATE = "KAFKA_CERTIFICATE"

const val KAFKA_CERTIFICATE_PATH = "KAFKA_CERTIFICATE_PATH"

const val KAFKA_PRIVATE_KEY = "KAFKA_PRIVATE_KEY"

const val KAFKA_PRIVATE_KEY_PATH = "KAFKA_PRIVATE_KEY_PATH"

const val KAFKA_CA = "KAFKA_CA"

const val KAFKA_CA_PATH = "KAFKA_CA_PATH"

const val KAFKA_CREDSTORE_PASSWORD = "KAFKA_CREDSTORE_PASSWORD"

const val KAFKA_KEYSTORE_PATH = "KAFKA_KEYSTORE_PATH"

const val KAFKA_TRUSTSTORE_PATH = "KAFKA_TRUSTSTORE_PATH"