name: Dolly API

on:
  push:
    branches:
      - main
    paths:
      - 'apps/dolly-api/**'
      - 'lib/**'
      - 'domain/**'
      - '.github/workflows/dolly-api.yaml'
      - 'gradle/**'
      - 'settings.gradle.kts'
      - 'gradle.properties'
      - 'gradlew'
      - 'gradlew.bat'
      - 'buildSrc/**'

env:
  MODULE: dolly-api
  IMAGE: europe-north1-docker.pkg.dev/nais-management-233d/paw/paw-arbeidssoekerregisteret-api-dolly
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      id-token: write
      packages: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Setup Java
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: Set version
        run: echo "VERSION=$(date +'%y.%m.%d').${{ github.run_number }}-${{ github.run_attempt }}" >> $GITHUB_ENV
      - name: Login GAR
        uses: nais/login@40b72a35a18ddf2ad74b632461139ab838cc2a2f # v0
        with:
          team: paw
      - name: Build and push image with Gradle
        id: docker-build-push
        working-directory: ./
        env:
          ORG_GRADLE_PROJECT_githubPassword: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "image=${{ env.IMAGE }}:${{ env.VERSION }}" >> $GITHUB_OUTPUT
          echo -Pversion=${{ env.VERSION }} -Pimage=${{ env.IMAGE }} :apps:${{ env.MODULE }}:build :apps:${{ env.MODULE }}:jib
          ./gradlew -Pversion=${{ env.VERSION }} -Pimage=${{ env.IMAGE }} :apps:${{ env.MODULE }}:build :apps:${{ env.MODULE }}:jib
          echo "DIGEST=$(cat ./apps/${{ env.MODULE }}/build/jib-image.digest)" >> $GITHUB_ENV
      - name: Attest and sign image
        uses: nais/attest-sign@65d1aaa8b7dc5913ae02b80f16f7c1cf9bad6491 # v2.0.17
        with:
          image_ref: ${{ env.IMAGE }}@${{ env.DIGEST }}

  deploy-dev:
    if: github.ref == 'refs/heads/main'
    name: Deploy to dev-gcp
    needs:
      - build
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Deploy to GCP
        uses: nais/deploy/actions/deploy@027a91857992525139798892f2804b0ca21f4af6 # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: ./apps/${{ env.MODULE }}/nais/nais-dev.yaml
          VAR: image=${{ needs.build.outputs.image }}
